## Please review configuration and adjust it for your own project
schema: ./packages/core/api/schema.graphql
extensions:
  graphback:
    model: ./packages/core/api/schema.graphql
    ## You can add as many Graphback plugins as you wish
    ## Here we are only adding the Schema and Client plugin
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./packages/core/api/schema.graphql
      graphback-client:
        format: 'graphql'
        outputFile: ./packages/core/api/schema.graphql
      graphback-datasync:
        format: 'graphql'
        packageName: '@graphback/datasync'
        outputPath: ./packages/core/api/schema.graphql