## Postgresql Database Graphql

sources:
  - name: Main
    handler:
      postgraphile:
        connectionString: DATABASE_URL
        # connectionString: postgres://{env.POSTGRES_USER}:{env.POSTGRES_PASSWORD}@localhost/postgres

# MySQL Database Graphql

#  - name: Employees
#    handler:
#      mysql:
#        # You can use environment variables like
#        # host: "{env.MYSQL_HOST}"
#        # port: "{env.MYSQL_PORT}"
#        # user: "{env.MYSQL_USER}"
#        # password: "{env.MYSQL_PASSWORD}"
#        # database: "{env.MYSQL_DATABASE}"
#        host: localhost
#        port: 3306
#        user: root
#        password: passwd
#        database: employees

# Sqlite Database Graphql

#  - name: MyDb
#    handler:
#      tuql:
#        db: path/to/database.sqlite

#  - name: Mongoose
#   handler:
#        mongoose:
#          connectionString: mongodb://localhost:27017/test
#          models:
#            - name: User
#              path: ./src/models#User

  - name: JsontoGraphql
    handler:
       openapi:
          source: ./prisma/schema.prisma

additionalTypeDefs: |
  extend type File {
    thumbnailImage(width: Int, height: Int): String
  }
additionalResolvers:
  - targetTypeName: File
    targetFieldName: thumbnailImage
    requiredSelectionSet: '{ base64 }'
    sourceName: ResizeImages
    sourceTypeName: Query
    sourceFieldName: resizeImage
    sourceArgs:
      image: '{root.base64}'
      width: '{args.width}'
      height: '{args.height}'

serve:
  cors:
    origin: '*'