
sources:
  - name: Main
    handler:
      postgraphile:
        connectionString: postgresql://postgres:Whurashia1986@db.wyhrhklrokwbwfwkgyoi.supabase.co:5432/postgres
        appendPlugins:
          - '@graphile/federation'
          - '@graphile-contrib/pg-many-to-many'
