
sources:
  - name: Main
    handler:
      postgraphile:
        connectionString: postgresql://{env.DB_USER}:{env.DB_PASSWORD}@{env.DB_HOST}:{env.DB_PORT}/{env.DB_DATABASE}
        appendPlugins:
          - '@graphile/federation'
          - '@graphile-contrib/pg-many-to-many'

serve:
  staticFiles: './media'
  playgroundTitle: 'AlternateCMS Graphql'