
query cases {
  findManyCases {
    accountName
    assignedTo
    caseNumber
    createdAt
    dateModified
    description
    id
    nodeId
    priority
    resolution
    state
    status
    subject
    type
  }
}