var wysiwygElement = document.getElementsByClassName('wysiwyg')[0];
var wysiwygInstance = new WYSIWYG(wysiwygElement, {
  translations : {
    paragraph: 'Paragraf',
    textStyle: 'Styl tekstu',
    heading: 'Nagłówek',
    preformatted: 'Pre-formatowany',
    bold: 'Pogrubienie',
    italic: 'Kursywa',
    strikethrough: 'Przekreślenie',
    underline: 'Podkreślenie',
    textcolor: 'Kolor tekstu',
    textBackgroundColor: 'kolor zaznaczenia',
    alignLeft: 'Wyśrodkowanie do lewej',
    alignCenter: 'Wyśrodkowanie do środka',
    alignRight: 'Wyśrodkowane do prawej',
    alignJustify: 'Justowanie',
    insertLink: 'Wstaw link',
    insertPicture: 'Wstaw obraz',
    unorderedList: 'Lista punktowa',
    orderedList: 'Lista numerowana',
    increaseIndent: 'Zwiększ wcięcie',
    decreaseIndent: 'Zmniejsz wcięcie',
    insertHorizontalRule: 'Wstaw linię poziomą',
    showHTML: 'Pokaż kod HTML',
    undo: 'Cofnij',
    redo: 'Przywróć',
    addLinkHead: 'Dodaj Link',
    addImageHead: 'Dodaj Obraz',
    linkUrlLabel: 'Wpisz adres:',
    linkDescription: 'Wpisz opis',
    imageUrlLabel: 'Wpisz adres obrazka:',
    okButton: 'OK',
    cancelButton: 'Anuluj',
    moreOptions: 'Pokaż więcej opcji',
  }
});