query surveys {
  surveys {
    answer
    assignedTo
    createdAt
    description
    dissatisfiedText
    id
    name
    neitherText
    nodeId
    question
    satisfiedText
    status
    submitText
  }
}