query MyQuery {
  allCustomersList(first: 5) {
    address
    addressTwo
    confirmedEmail
    country
    customerGroup
    customerSince
    dateOfBirth
    description
    email
    firstName
    gender
    id
    image
    lastName
    middleName
    namePrefix
    nameSuffix
    nodeId
    password
    paymentType
    phone
    product
    shortDescription
    state
    taxVatNumber
    thumbnail
    username
    zipcode
    websites
  }
}