query MyQuery {
  meeting {
    id
    assigned_to
    content
    created_at
    duration
    end_date
    invitees
    related_to
    reminders
    scheduling
    start_date
    status
    subject
  }
}