query MyQuery {
  allMeetingsList {
    assignedTo
    content
    createdAt
    duration
    endDate
    id
    invitees
    nodeId
    relatedTo
    reminders
    scheduling
    startDate
    status
    subject
  }
}