query articles {
  articles {
    id
    excerpt
    customers
    custId
    content
    categories
    image
    isPublic
    metaDescription
    metaName
    metaUrl
    name
    nodeId
    published
    tags
    users
  }
}