query allMediamanagersList {
  allMediamanagersList {
    agreements
    albums
    author
    brands
    comment
    contentType
    copyright
    createdAt
    description
    dimensions
    expirationDate
    id
    keywords
    media
    members
    name
    nodeId
    products
    status
    tags
    taskDescription
    taskName
    taskType
    versions
    watermarkDescription
    watermarkMedia
    watermarkName
    workspace
  }
}