query projects {
  projects {
    id
    name
    nodeId
    priority
    projectManager
    projectTemplate
    resource
    sectionRule
    staffId
    startDate
    status
    ticketId
    taskId
    goalUpdatemethod
    goalTimeperiod
    goalProgressSource
    goalPrivacy
    goalName
    goalMeasurement
    goalCollaborators
    endDate
    done
    doing
    custId
    createdAt
    considerworkingdays
    assignee
  }
}