query MyQuery {
  findManyProjects {
    assignee
    considerworkingdays
    cust_id
    customers
    doing
    done
    end_date
    goal_collaborators
    goal_measurement
    goal_name
    goal_privacy
    goal_progress_source
    goal_timeperiod
    goal_updatemethod
    name
    priority
    project_manager
    project_template
    resource
    section_rule
    staff_id
    start_date
    status
    task_id
    tasks
    ticket_id
    ticketing
    users
    workspaces
    id
    created_at
  }
}