query MyQuery {
  findManySettings {
    address
    address_two
    allow_countries
    allowed_currency
    allow_state
    awsS3
    base_currency
    city
    created_at
    country
    databaseUrl
    default_country
    default_currency
    disqusKey
    european_union_countries
    googleDrive
    id
    isPublic
    mailServer
    optional_zip
    region
    searchSetting
    sentryDsn
    siteName
    siteTagline
    siteWebsite
    state_required_for
    store_hours
    store_name
    store_phone
    top_destinations
    type
    vat_number
    youtubeVideos
    zipcode
  }
}