query MyQuery {
  general_settings {
    id
    http_response
    email
    customer_support
    created_at
    access_restrictions
    landing_page
    restriction_mode
    startup_page
    store_contact
    store_contact_two
    store_email
    tagline
    title
    url
  }
}
