query generalSettings {
  generalSettings {
    accessRestrictions
    createdAt
    customerSupport
    email
    httpResponse
    id
    landingPage
    restrictionMode
    nodeId
    startupPage
    storeContact
    storeContactTwo
    storeEmail
    tagline
    title
    url
  }
}