subscription MySubscription {
  _entities(representations: "") {
    ... on _User {
      createdAt
      updatedAt
    }
    ... on _Role {
      createdAt
      updatedAt
    }
    ... on Zone {
      id
      name
    }
    ... on Webhook {
      id
      name
    }
    ... on Warehouse {
      id
      name
    }
    ... on Visit {
      id
    }
    ... on UrlRewrite {
      id
    }
    ... on UploadFileMorph {
      id
    }
    ... on UploadFile {
      id
      name
    }
    ... on Theme {
      id
    }
    ... on Website {
      id
      name
    }
    ... on TaxCategory {
      id
      name
    }
    ... on Target {
      id
      email
    }
    ... on Tag {
      id
      name
    }
    ... on Survey {
      id
      name
    }
    ... on Stock {
      id
      name
    }
    ... on Statistic {
      id
      name
    }
    ... on SpecialDiscount {
      id
      name
    }
    ... on Source {
      id
      email
    }
    ... on ShopSetting {
      id
    }
    ... on Shipment {
      id
    }
    ... on Settingssale {
      id
    }
    ... on Settingsmarketing {
      id
    }
    ... on Settingshop {
      id
    }
    ... on Settingsgeneral {
      id
      email
    }
    ... on Settingscustomer {
      id
    }
    ... on Segment {
      id
      name
    }
    ... on Reward {
      id
      name
    }
    ... on Review {
      id
    }
    ... on Report {
      id
      email
    }
    ... on Provider {
      id
      name
    }
    ... on ProjectTemplate {
      id
      name
    }
    ... on Plugin {
      id
      name
    }
    ... on Poll {
      id
      name
    }
    ... on Permission {
      id
      name
    }
    ... on PdfTemplate {
      id
      name
    }
    ... on Payment {
      id
      name
    }
    ... on Partner {
      id
      name
    }
    ... on Page {
      id
    }
    ... on Opportunity {
      id
      name
    }
    ... on Ooto {
      id
    }
    ... on Meeting {
      id
    }
    ... on Lead {
      id
      email
    }
    ... on Knowledgebase {
      id
      name
    }
    ... on Invoice {
      id
      email
    }
    ... on Invitation {
      id
      email
    }
    ... on Internalization {
      id
      name
    }
    ... on Integration {
      id
      name
    }
    ... on Importm {
      id
      name
    }
    ... on Glossary {
      id
      name
    }
    ... on GiftCertificate {
      id
      name
    }
    ... on GeneralSetting {
      id
      email
    }
    ... on Fullfillment {
      id
      name
    }
    ... on Event {
      id
      name
    }
    ... on EmailTemplate {
      id
      name
    }
    ... on Deepdive {
      id
    }
    ... on Dashboard {
      id
      name
    }
    ... on Customization {
      id
      email
    }
    ... on CurrencySymbol {
      useStandard
    }
    ... on CurrencyRate {
      usd
    }
    ... on Currency {
      id
      name
    }
    ... on CoreStore {
      id
    }
    ... on Contract {
      id
    }
    ... on ContentType {
      id
      email
    }
    ... on Collection {
      id
      name
    }
    ... on City {
      id
      name
    }
    ... on Channel {
      id
      name
    }
    ... on CatalogPriceRule {
      id
    }
    ... on Case {
      id
    }
    ... on CartPriceRule {
      id
    }
    ... on Article {
      id
      name
    }
    ... on Apitoken {
      id
      name
    }
    ... on Analytic {
      id
      name
    }
    ... on Account {
      id
      email
    }
    ... on Message {
      id
    }
    ... on CustomerGroup {
      id
      name
    }
    ... on NewsletterSubscriber {
      id
      email
    }
    ... on Checklist {
      id
    }
    ... on State {
      id
      name
    }
    ... on Country {
      id
      name
    }
    ... on Training {
      id
      name
    }
    ... on Agreement {
      id
      name
    }
    ... on Category {
      id
      name
    }
    ... on Shop {
      id
      name
    }
    ... on Ticketing {
      id
      name
    }
    ... on Project {
      id
      name
    }
    ... on Task {
      id
    }
    ... on Workspace {
      id
      name
    }
    ... on Manufacturer {
      id
      name
    }
    ... on Wishlist {
      id
      name
    }
    ... on Occassion {
      id
      name
    }
    ... on ProductType {
      id
    }
    ... on Return {
      id
      name
    }
    ... on TaxRule {
      id
      name
    }
    ... on TaxRate {
      id
    }
    ... on Rating {
      id
    }
    ... on ProductAttributeSet {
      id
      name
    }
    ... on ProductAttribute {
      id
    }
    ... on CustomerPayment {
      id
    }
    ... on Transaction {
      id
    }
    ... on Quote {
      id
      name
    }
    ... on CreditMemo {
      id
    }
    ... on Order {
      id
    }
    ... on Coupon {
      id
      name
    }
    ... on Product {
      id
      name
    }
    ... on Brand {
      id
      name
    }
    ... on Mediamanager {
      id
      name
    }
    ... on Comment {
      id
    }
    ... on Customer {
      id
      email
    }
    ... on Email {
      id
    }
    ... on User {
      id
      email
    }
    ... on Endofshift {
      id
    }
    ... on Scheduler {
      id
    }
    ... on _Audience {
      createdAt
      updatedAt
    }
    ... on _Schema {
      schema
      isParseClass
    }
    ... on Role {
      id
    }
    ... on _PushStatus {
      createdAt
      updatedAt
    }
    ... on _JoinUsersRole {
      __typename
    }
    ... on _JoinRolesRole {
      __typename
    }
    ... on _JobStatus {
      createdAt
      updatedAt
    }
    ... on _JobSchedule {
      createdAt
      updatedAt
    }
    ... on _Idempotency {
      createdAt
      updatedAt
    }
    ... on _GraphQlConfig {
      config
    }
    ... on _GlobalConfig {
      params
      masterKeyOnly
    }
  }
}