query allCreditMemosList {
  allCreditMemosList {
    action
    billToName
    created
    creditMemo
    custId
    id
    nodeId
    orderNumber
    prodId
    refunded
    status
    customerByCustId {
      id
      firstName
      lastName
    }
    productByProdId {
      id
      name
      price
    }
  }
}