query allOrdersList {
  allOrdersList {
    action
    allocatedSources
    billToName
    braintreeTransactionSource
    custId
    grandTotalBase
    grandTotalPurchased
    id
    nodeId
    prodId
    purchaseDate
    purchasePoint
    status
    shipToName
  }
}