query MyQuery {
  allShipmentsList {
    carrierName
    clientId
    clientSecret
    country
    id
    image
    nodeId
    product
    shipDate
    speedGrade
    trackingUrl
    transitTime
    website
  }
}