query transactions {
  transactions {
    closed
    created
    id
    nodeId
    orderId
    parentTransactionId
    paymentMethod
    transactionId
    orderByOrderId {
      id
      billToName
    }
    customerPaymentByPaymentMethod {
      id
      provider
    }
  }
}