query {
  aggregateCollections 
 {
    _avg {
      id
    }
    _count {
      _all
      created_at
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      name
      product
    }
    _max {
      created_at
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      name
      product
    }
    _min {
      created_at
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      name
      product
    }
    _sum {
      id
    }
  }
}
