query {
  aggregateUpload_file 
 {
    _avg {
      created_by
      height
      id
      size
      updated_by
      width
    }
    _count {
      _all
      alternativeText
      caption
      created_at
      created_by
      ext
      formats
      hash
      height
      id
      mime
      name
      previewUrl
      provider
      provider_metadata
      size
      updated_at
      updated_by
      url
      width
    }
    _max {
      alternativeText
      caption
      created_at
      created_by
      ext
      hash
      height
      id
      mime
      name
      previewUrl
      provider
      size
      updated_at
      updated_by
      url
      width
    }
    _min {
      alternativeText
      caption
      created_at
      created_by
      ext
      hash
      height
      id
      mime
      name
      previewUrl
      provider
      size
      updated_at
      updated_by
      url
      width
    }
    _sum {
      created_by
      height
      id
      size
      updated_by
      width
    }
  }
}
