query {
  aggregateAccounts 
 {
    _avg {
      id
    }
    _count {
      _all
      address
      alt_address
      alt_city
      alt_country
      alt_postalcode
      alt_state
      annual_revenue
      assigned_to
      campaign
      city
      country
      created_at
      email
      employees
      fax
      id
      industry
      member_of
      name
      office_phone
      postalcode
      state
      type
      website
    }
    _max {
      address
      alt_address
      alt_city
      alt_country
      alt_postalcode
      alt_state
      annual_revenue
      assigned_to
      campaign
      city
      country
      created_at
      email
      employees
      fax
      id
      industry
      member_of
      name
      office_phone
      postalcode
      state
      type
      website
    }
    _min {
      address
      alt_address
      alt_city
      alt_country
      alt_postalcode
      alt_state
      annual_revenue
      assigned_to
      campaign
      city
      country
      created_at
      email
      employees
      fax
      id
      industry
      member_of
      name
      office_phone
      postalcode
      state
      type
      website
    }
    _sum {
      id
    }
  }
}
