query {
  aggregateEndofshift 
 {
    _avg {
      id
    }
    _count {
      _all
      content
      created_at
      id
      login
      mcms
      next_shift
      projects
      tickets
      whid
    }
    _max {
      content
      created_at
      id
      login
      mcms
      next_shift
      projects
      tickets
      whid
    }
    _min {
      content
      created_at
      id
      login
      mcms
      next_shift
      projects
      tickets
      whid
    }
    _sum {
      id
    }
  }
}
