query {
  aggregateTicketing 
 {
    _avg {
      id
    }
    _count {
      _all
      account_name
      assigned_to
      comment
      content
      created_at
      date
      date_modified
      department
      id
      level
      location
      media
      name
      priority
      products
      projects
      projects_projectsToticketing
      requester
      requester_email
      resolution
      severity
      status
      team
      ticket_type
    }
    _max {
      account_name
      assigned_to
      comment
      content
      created_at
      date
      date_modified
      department
      id
      level
      location
      media
      name
      priority
      products
      projects
      projects_projectsToticketing
      requester
      requester_email
      resolution
      severity
      status
      team
      ticket_type
    }
    _min {
      account_name
      assigned_to
      comment
      content
      created_at
      date
      date_modified
      department
      id
      level
      location
      media
      name
      priority
      products
      projects
      projects_projectsToticketing
      requester
      requester_email
      resolution
      severity
      status
      team
      ticket_type
    }
    _sum {
      id
    }
  }
}
