query {
  aggregateDashboardrestapi 
 {
    _avg {
      id
    }
    _count {
      _all
      authenticationType
      description
      headerKey
      headerValue
      id
      name
      url
    }
    _max {
      authenticationType
      description
      headerKey
      headerValue
      id
      name
      url
    }
    _min {
      authenticationType
      description
      headerKey
      headerValue
      id
      name
      url
    }
    _sum {
      id
    }
  }
}
