query {
  aggregateEvents 
 {
    _avg {
      id
    }
    _count {
      _all
      category
      city
      content
      country
      created_at
      end
      id
      image
      invitationBillingAddress
      invitationCustomerName
      invitationEmail
      invitationGrandTotalPurchased
      invitationInvoiceDate
      invitationOrderNumber
      invitationPaymentMethod
      invitationShippingAddress
      invitationStatus
      media
      name
      postalcode
      start
      state
      tickets
      type
    }
    _max {
      category
      city
      content
      country
      created_at
      end
      id
      image
      invitationBillingAddress
      invitationCustomerName
      invitationEmail
      invitationGrandTotalPurchased
      invitationInvoiceDate
      invitationOrderNumber
      invitationPaymentMethod
      invitationShippingAddress
      invitationStatus
      media
      name
      postalcode
      start
      state
      tickets
      type
    }
    _min {
      category
      city
      content
      country
      created_at
      end
      id
      image
      invitationBillingAddress
      invitationCustomerName
      invitationEmail
      invitationGrandTotalPurchased
      invitationInvoiceDate
      invitationOrderNumber
      invitationPaymentMethod
      invitationShippingAddress
      invitationStatus
      media
      name
      postalcode
      start
      state
      tickets
      type
    }
    _sum {
      id
    }
  }
}
