query {
  aggregateCategories 
 {
    _avg {
      id
    }
    _count {
      _all
      content
      country
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      meta_url
      name
      product
      status
      thumbnail
      visibility
      websites
      workspaces
    }
    _max {
      content
      country
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      meta_url
      name
      product
      status
      thumbnail
      visibility
      websites
      workspaces
    }
    _min {
      content
      country
      description
      id
      image
      meta_description
      meta_keywords
      meta_title
      meta_url
      name
      product
      status
      thumbnail
      visibility
      websites
      workspaces
    }
    _sum {
      id
    }
  }
}
