query {
  aggregateDiscounts 
 {
    _avg {
      id
    }
    _count {
      _all
      articles
      billToName
      categories
      coupons
      creditMemo
      customers
      discount
      excerpt
      expiration
      id
      image
      name
      orderNumber
      products
      published
      refunded
      rewards
      special_offers
      status
      type
      users
    }
    _max {
      articles
      billToName
      categories
      coupons
      creditMemo
      customers
      discount
      excerpt
      expiration
      id
      image
      name
      orderNumber
      products
      published
      refunded
      rewards
      special_offers
      status
      type
      users
    }
    _min {
      articles
      billToName
      categories
      coupons
      creditMemo
      customers
      discount
      excerpt
      expiration
      id
      image
      name
      orderNumber
      products
      published
      refunded
      rewards
      special_offers
      status
      type
      users
    }
    _sum {
      id
    }
  }
}
