query {
  aggregateStocks 
 {
    _avg {
      id
    }
    _count {
      _all
      description
      enabled
      id
      name
      sources
      website
    }
    _max {
      description
      enabled
      id
      name
      sources
      website
    }
    _min {
      description
      enabled
      id
      name
      sources
      website
    }
    _sum {
      id
    }
  }
}
