query {
  aggregateThemes 
 {
    _avg {
      id
      website_id
    }
    _count {
      _all
      action
      id
      parent_theme
      theme_path
      title
      website_id
      websites
    }
    _max {
      action
      id
      parent_theme
      theme_path
      title
      website_id
      websites
    }
    _min {
      action
      id
      parent_theme
      theme_path
      title
      website_id
      websites
    }
    _sum {
      id
      website_id
    }
  }
}
