query {
  findManySettings 
 {
    address
    address_two
    allow_countries
    allow_state
    allowed_currency
    awsS3
    base_currency
    city
    country
    created_at
    databaseUrl
    default_country
    default_currency
    european_union_countries
    googleAnalytics
    id
    isPublic
    mailServer
    optional_zip
    region
    searchSetting
    sentryDsn
    siteName
    siteTagline
    siteWebsite
    state_required_for
    store_hours
    store_name
    store_phone
    top_destinations
    type
    vat_number
    zipcode
  }
}
