query {
  findFirstChecklist 
 {
    country
    created_at
    description
    id
    location
    manager
    media
    prod_id
    project
    region
    regional_manager
    task
    ticket
    trainings
    type
    username
  }
}
