query {
  findManyBrands 
 {
    city
    code
    country
    created_at
    description
    id
    isPublic
    media
    mediamanager
    name
    product
    products
    state
    workspaces
  }
}
