query {
  findUniqueFullfillmentsOrThrow 
 {
    address
    address_two
    city
    company
    country
    country_area
    created_at
    id
    name
    phone
    pickup
    shipping_zones
    state
    stock
    zipcode
  }
}
