query {
  findFirstUsersOrThrow 
 {
    created_at
    email
    emails
    first_name
    id
    interface_locale
    last_name
    mediamanager
    messages
    password
    permissions
    projects
    username
    value
    workspaces
  }
}
