query {
  getUpload_file 
 {
    alternativeText
    caption
    created_at
    created_by
    ext
    formats
    hash
    height
    id
    mime
    name
    previewUrl
    provider
    provider_metadata
    size
    updated_at
    updated_by
    url
    width
  }
}
