query {
  groupByOrders 
 {
    _avg {
      cust_id
      grand_total_base
      grand_total_purchased
      id
      prod_id
      purchase_point
    }
    _count {
      _all
      action
      allocated_sources
      bill_to_name
      braintree_transaction_source
      cust_id
      customers
      grand_total_base
      grand_total_purchased
      id
      prod_id
      products
      purchase_date
      purchase_point
      quotes
      ship_to_name
      status
      transactions
    }
    _max {
      action
      allocated_sources
      bill_to_name
      braintree_transaction_source
      cust_id
      customers
      grand_total_base
      grand_total_purchased
      id
      prod_id
      products
      purchase_date
      purchase_point
      quotes
      ship_to_name
      status
      transactions
    }
    _min {
      action
      allocated_sources
      bill_to_name
      braintree_transaction_source
      cust_id
      customers
      grand_total_base
      grand_total_purchased
      id
      prod_id
      products
      purchase_date
      purchase_point
      quotes
      ship_to_name
      status
      transactions
    }
    _sum {
      cust_id
      grand_total_base
      grand_total_purchased
      id
      prod_id
      purchase_point
    }
    action
    allocated_sources
    bill_to_name
    braintree_transaction_source
    cust_id
    customers
    grand_total_base
    grand_total_purchased
    id
    prod_id
    products
    purchase_date
    purchase_point
    quotes
    ship_to_name
    status
    transactions
  }
}
