query {
  groupByChannels 
 {
    _avg {
      id
    }
    _count {
      _all
      client_id
      client_secret
      code
      created_at
      currency
      default_lang
      default_shipping
      default_zone
      id
      include_tax
      name
    }
    _max {
      client_id
      client_secret
      code
      created_at
      currency
      default_lang
      default_shipping
      default_zone
      id
      include_tax
      name
    }
    _min {
      client_id
      client_secret
      code
      created_at
      currency
      default_lang
      default_shipping
      default_zone
      id
      include_tax
      name
    }
    _sum {
      id
    }
    client_id
    client_secret
    code
    created_at
    currency
    default_lang
    default_shipping
    default_zone
    id
    include_tax
    name
  }
}
