query {
  groupByReturns 
 {
    _avg {
      id
    }
    _count {
      _all
      case_id
      created_at
      customers
      description
      height
      howShipped
      id
      liquidationReason
      location
      media
      name
      products
      return_prefix
      shipTo
      shippingDescription
      shippingNumber
      status
      type
      validity
      weight
    }
    _max {
      case_id
      created_at
      customers
      description
      height
      howShipped
      id
      liquidationReason
      location
      media
      name
      products
      return_prefix
      shipTo
      shippingDescription
      shippingNumber
      status
      type
      validity
      weight
    }
    _min {
      case_id
      created_at
      customers
      description
      height
      howShipped
      id
      liquidationReason
      location
      media
      name
      products
      return_prefix
      shipTo
      shippingDescription
      shippingNumber
      status
      type
      validity
      weight
    }
    _sum {
      id
    }
    case_id
    created_at
    customers
    description
    height
    howShipped
    id
    liquidationReason
    location
    media
    name
    products
    return_prefix
    shipTo
    shippingDescription
    shippingNumber
    status
    type
    validity
    weight
  }
}
