query {
  groupByDashboards 
 {
    _avg {
      id
    }
    _count {
      _all
      articles
      category
      checklists
      client_id
      client_secret
      content
      created_at
      customers
      id
      logo
      media
      name
      privacy
      products
      projects
      published
      reports
      sales
      tasks
      tickets
      url
      users
      visits
    }
    _max {
      articles
      category
      checklists
      client_id
      client_secret
      content
      created_at
      customers
      id
      logo
      media
      name
      privacy
      products
      projects
      published
      reports
      sales
      tasks
      tickets
      url
      users
      visits
    }
    _min {
      articles
      category
      checklists
      client_id
      client_secret
      content
      created_at
      customers
      id
      logo
      media
      name
      privacy
      products
      projects
      published
      reports
      sales
      tasks
      tickets
      url
      users
      visits
    }
    _sum {
      id
    }
    articles
    category
    checklists
    client_id
    client_secret
    content
    created_at
    customers
    id
    logo
    media
    name
    privacy
    products
    projects
    published
    reports
    sales
    tasks
    tickets
    url
    users
    visits
  }
}
