query {
  groupByDashboardslides 
 {
    _avg {
      id
    }
    _count {
      _all
      categories
      description
      id
      media
      name
    }
    _max {
      categories
      description
      id
      media
      name
    }
    _min {
      categories
      description
      id
      media
      name
    }
    _sum {
      id
    }
    categories
    description
    id
    media
    name
  }
}
