query {
  groupByCountries 
 {
    _avg {
      id
    }
    _count {
      _all
      description
      id
      image
      name
      region
      trainings
    }
    _max {
      description
      id
      image
      name
      region
      trainings
    }
    _min {
      description
      id
      image
      name
      region
      trainings
    }
    _sum {
      id
    }
    description
    id
    image
    name
    region
    trainings
  }
}
