query {
  groupByContracts 
 {
    _avg {
      id
    }
    _count {
      _all
      account
      company_signed_date
      contact
      contract_manager
      contract_title
      contract_type
      contract_value
      created_at
      currency
      customer_signed_date
      description
      discount
      end_date
      grand_total
      id
      line_items
      opportunity
      renewal_reminder
      shipping
      shipping_tax
      start_date
      status
      subtotal
      tax
      total
    }
    _max {
      account
      company_signed_date
      contact
      contract_manager
      contract_title
      contract_type
      contract_value
      created_at
      currency
      customer_signed_date
      description
      discount
      end_date
      grand_total
      id
      line_items
      opportunity
      renewal_reminder
      shipping
      shipping_tax
      start_date
      status
      subtotal
      tax
      total
    }
    _min {
      account
      company_signed_date
      contact
      contract_manager
      contract_title
      contract_type
      contract_value
      created_at
      currency
      customer_signed_date
      description
      discount
      end_date
      grand_total
      id
      line_items
      opportunity
      renewal_reminder
      shipping
      shipping_tax
      start_date
      status
      subtotal
      tax
      total
    }
    _sum {
      id
    }
    account
    company_signed_date
    contact
    contract_manager
    contract_title
    contract_type
    contract_value
    created_at
    currency
    customer_signed_date
    description
    discount
    end_date
    grand_total
    id
    line_items
    opportunity
    renewal_reminder
    shipping
    shipping_tax
    start_date
    status
    subtotal
    tax
    total
  }
}
