// Generated by nuxi
/// <reference types="@nuxtjs/moment" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/pwa" />
/// <reference types="@nuxtjs/sentry" />
/// <reference types="@nuxtjs/apollo" />
/// <reference types="@nuxt/http" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxt/image" />
/// <reference types="@nuxt/image" />
/// <reference types="nuxt-client-init-module" />
/// <reference types="nuxtjs-darkmode-js-module" />
/// <reference types="nuxt-stripe-module" />
/// <reference types="@nuxtjs/lunr-module" />
/// <reference types="nuxt-highcharts" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />

export {}
