// Generated by nuxi
/// <reference types="@nuxtjs/apollo" />
/// <reference types="@nuxt/content" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="nuxt-security" />
/// <reference types="nuxt-meilisearch" />
/// <reference types="nuxt-directus" />
/// <reference types="@huntersofbook/naive-ui-nuxt" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="types/content.d.ts" />
/// <reference path="../node_modules/@nuxtjs/i18n/dist/runtime/types" />
/// <reference path="types/naive-ui.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
