import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _8c3791c0 = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _2e61864a = () => interopDefault(import('..\\pages\\search.vue' /* webpackChunkName: "pages/search" */))
const _708cdab4 = () => interopDefault(import('..\\pages\\test.vue' /* webpackChunkName: "pages/test" */))
const _e181e7a6 = () => interopDefault(import('..\\pages\\Auth\\Forgot.vue' /* webpackChunkName: "pages/Auth/Forgot" */))
const _1d818162 = () => interopDefault(import('..\\pages\\Auth\\Login.vue' /* webpackChunkName: "pages/Auth/Login" */))
const _250d39a6 = () => interopDefault(import('..\\pages\\Auth\\Register.vue' /* webpackChunkName: "pages/Auth/Register" */))
const _5f4beb96 = () => interopDefault(import('..\\pages\\Auth\\Reset.vue' /* webpackChunkName: "pages/Auth/Reset" */))
const _beb522ce = () => interopDefault(import('..\\pages\\User\\my-account.vue' /* webpackChunkName: "pages/User/my-account" */))
const _1bc74b8c = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-agreement.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-agreement" */))
const _5cc64526 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-article.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-article" */))
const _19d819cc = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-attribute.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-attribute" */))
const _606c8e10 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-campaign.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-campaign" */))
const _28496c30 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-case.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-case" */))
const _6f8aa2fe = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-category.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-category" */))
const _3c5826b3 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-channel.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-channel" */))
const _4c7eabd6 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-checklist.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-checklist" */))
const _5b6c162a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-city.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-city" */))
const _a9866ac4 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-collection.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-collection" */))
const _028ccd12 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-contract.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-contract" */))
const _58030074 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-country.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-country" */))
const _494337b4 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-coupon.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-coupon" */))
const _dbe3d6de = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-currency.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-currency" */))
const _e8661444 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-customer.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-customer" */))
const _6c8dabde = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-customergroup.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-customergroup" */))
const _6a22d9e0 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-deepdive.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-deepdive" */))
const _39e746cc = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-email.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-email" */))
const _4a7fd0c6 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-emailtemplates.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-emailtemplates" */))
const _454b95ee = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-eosr.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-eosr" */))
const _8538826c = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-event.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-event" */))
const _53db7ea8 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-fullfilment.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-fullfilment" */))
const _a484482e = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-gift-certificates.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-gift-certificates" */))
const _446aa01e = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-glossary.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-glossary" */))
const _0ec07046 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-invoice.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-invoice" */))
const _94475c02 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-knowledgebase.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-knowledgebase" */))
const _f7f0cb48 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-lead.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-lead" */))
const _114cd02a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-meeting.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-meeting" */))
const _fdbec98e = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-newsletter.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-newsletter" */))
const _95ec6cf8 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-newslettersubscriber copy.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-newslettersubscriber copy" */))
const _249ef04a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-ooto.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-ooto" */))
const _4ab7c6fa = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-opportunity.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-opportunity" */))
const _5a3e8c0f = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-page.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-page" */))
const _661a1bf8 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-partner.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-partner" */))
const _39508807 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-pdftemplates.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-pdftemplates" */))
const _59cebec2 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-product.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-product" */))
const _5c5ca759 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-producttype.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-producttype" */))
const _18080c6e = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-project.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-project" */))
const _631fc9ac = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-quote.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-quote" */))
const _2a26aa34 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-report.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-report" */))
const _06bc3430 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-return.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-return" */))
const _46039a58 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-review.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-review" */))
const _629b4854 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-rewards.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-rewards" */))
const _17205e76 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-role.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-role" */))
const _c92ff7d2 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-schedule.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-schedule" */))
const _19969e3a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-segment.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-segment" */))
const _33dda99a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-shipment.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-shipment" */))
const _126f78f6 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-shop.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-shop" */))
const _eec3328e = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-staffmembers.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-staffmembers" */))
const _3f303d41 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-state.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-state" */))
const _e2470d4c = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-survey.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-survey" */))
const _62cd51ca = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-tag.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-tag" */))
const _57ed5fde = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-target.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-target" */))
const _0e91f405 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-task.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-task" */))
const _6694b68a = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-taxrate.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-taxrate" */))
const _3de8fe52 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-taxrule.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-taxrule" */))
const _3394140c = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-ticket.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-ticket" */))
const _2b8ed8fb = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-visit.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-visit" */))
const _25dd3e73 = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-warehouse.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-warehouse" */))
const _599376ac = () => interopDefault(import('..\\pages\\Admin\\Add-New\\add-new-zone.vue' /* webpackChunkName: "pages/Admin/Add-New/add-new-zone" */))
const _9d529964 = () => interopDefault(import('..\\pages\\Admin\\Content\\blog.vue' /* webpackChunkName: "pages/Admin/Content/blog" */))
const _98c3f46c = () => interopDefault(import('..\\pages\\Admin\\Content\\glossary.vue' /* webpackChunkName: "pages/Admin/Content/glossary" */))
const _52b993c8 = () => interopDefault(import('..\\pages\\Admin\\Content\\media-manager.vue' /* webpackChunkName: "pages/Admin/Content/media-manager" */))
const _77a0f0c8 = () => interopDefault(import('..\\pages\\Admin\\Content\\pages.vue' /* webpackChunkName: "pages/Admin/Content/pages" */))
const _033b73b4 = () => interopDefault(import('..\\pages\\Admin\\Content\\projects.vue' /* webpackChunkName: "pages/Admin/Content/projects" */))
const _a76cb776 = () => interopDefault(import('..\\pages\\Admin\\Content\\tags.vue' /* webpackChunkName: "pages/Admin/Content/tags" */))
const _721d0311 = () => interopDefault(import('..\\pages\\Admin\\Customers\\all-customers.vue' /* webpackChunkName: "pages/Admin/Customers/all-customers" */))
const _47c4b57f = () => interopDefault(import('..\\pages\\Admin\\Customers\\leads.vue' /* webpackChunkName: "pages/Admin/Customers/leads" */))
const _1b5b8f40 = () => interopDefault(import('..\\pages\\Admin\\Customers\\meetings.vue' /* webpackChunkName: "pages/Admin/Customers/meetings" */))
const _4c8afaa3 = () => interopDefault(import('..\\pages\\Admin\\Customers\\online-customers.vue' /* webpackChunkName: "pages/Admin/Customers/online-customers" */))
const _fd636ace = () => interopDefault(import('..\\pages\\Admin\\Customers\\opportunities.vue' /* webpackChunkName: "pages/Admin/Customers/opportunities" */))
const _71da3e68 = () => interopDefault(import('..\\pages\\Admin\\Customers\\segments.vue' /* webpackChunkName: "pages/Admin/Customers/segments" */))
const _2109ea9c = () => interopDefault(import('..\\pages\\Admin\\Customers\\social-groups.vue' /* webpackChunkName: "pages/Admin/Customers/social-groups" */))
const _0e8590f6 = () => interopDefault(import('..\\pages\\Admin\\Customers\\tasks.vue' /* webpackChunkName: "pages/Admin/Customers/tasks" */))
const _6c07dba6 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\checklists.vue' /* webpackChunkName: "pages/Admin/Marketing/checklists" */))
const _334552f6 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\communications.vue' /* webpackChunkName: "pages/Admin/Marketing/communications" */))
const _d40a98d0 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\contracts.vue' /* webpackChunkName: "pages/Admin/Marketing/contracts" */))
const _1416489c = () => interopDefault(import('..\\pages\\Admin\\Marketing\\events.vue' /* webpackChunkName: "pages/Admin/Marketing/events" */))
const _7fd3cdb1 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\invitations.vue' /* webpackChunkName: "pages/Admin/Marketing/invitations" */))
const _b3b3f25c = () => interopDefault(import('..\\pages\\Admin\\Marketing\\newsletter.vue' /* webpackChunkName: "pages/Admin/Marketing/newsletter" */))
const _3ceb965c = () => interopDefault(import('..\\pages\\Admin\\Marketing\\reviews.vue' /* webpackChunkName: "pages/Admin/Marketing/reviews" */))
const _73eba94a = () => interopDefault(import('..\\pages\\Admin\\Marketing\\rewards.vue' /* webpackChunkName: "pages/Admin/Marketing/rewards" */))
const _311ab394 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\seo.vue' /* webpackChunkName: "pages/Admin/Marketing/seo" */))
const _ba50fe66 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\ticketing.vue' /* webpackChunkName: "pages/Admin/Marketing/ticketing" */))
const _bcf7c29a = () => interopDefault(import('..\\pages\\Admin\\Marketing\\training.vue' /* webpackChunkName: "pages/Admin/Marketing/training" */))
const _4d2d07a1 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\visits.vue' /* webpackChunkName: "pages/Admin/Marketing/visits" */))
const _ebc5751a = () => interopDefault(import('..\\pages\\Admin\\Reports\\calendars.vue' /* webpackChunkName: "pages/Admin/Reports/calendars" */))
const _5b4be07e = () => interopDefault(import('..\\pages\\Admin\\Reports\\cases.vue' /* webpackChunkName: "pages/Admin/Reports/cases" */))
const _0c2d9eb3 = () => interopDefault(import('..\\pages\\Admin\\Reports\\deep-dive.vue' /* webpackChunkName: "pages/Admin/Reports/deep-dive" */))
const _79ab0e7b = () => interopDefault(import('..\\pages\\Admin\\Reports\\eosr.vue' /* webpackChunkName: "pages/Admin/Reports/eosr" */))
const _ebfd3d66 = () => interopDefault(import('..\\pages\\Admin\\Reports\\ooto.vue' /* webpackChunkName: "pages/Admin/Reports/ooto" */))
const _7a3ad286 = () => interopDefault(import('..\\pages\\Admin\\Reports\\reports.vue' /* webpackChunkName: "pages/Admin/Reports/reports" */))
const _c71502d6 = () => interopDefault(import('..\\pages\\Admin\\Reports\\statistics.vue' /* webpackChunkName: "pages/Admin/Reports/statistics" */))
const _1632a752 = () => interopDefault(import('..\\pages\\Admin\\Reports\\surveys.vue' /* webpackChunkName: "pages/Admin/Reports/surveys" */))
const _879bdc86 = () => interopDefault(import('..\\pages\\Admin\\Reports\\team-scheduler.vue' /* webpackChunkName: "pages/Admin/Reports/team-scheduler" */))
const _83855bb0 = () => interopDefault(import('..\\pages\\Admin\\Sales\\agreements.vue' /* webpackChunkName: "pages/Admin/Sales/agreements" */))
const _ee72d60a = () => interopDefault(import('..\\pages\\Admin\\Sales\\certificates.vue' /* webpackChunkName: "pages/Admin/Sales/certificates" */))
const _b68f0d38 = () => interopDefault(import('..\\pages\\Admin\\Sales\\credit-memos.vue' /* webpackChunkName: "pages/Admin/Sales/credit-memos" */))
const _6db68ca5 = () => interopDefault(import('..\\pages\\Admin\\Sales\\invoices.vue' /* webpackChunkName: "pages/Admin/Sales/invoices" */))
const _441412e4 = () => interopDefault(import('..\\pages\\Admin\\Sales\\orders.vue' /* webpackChunkName: "pages/Admin/Sales/orders" */))
const _636fa876 = () => interopDefault(import('..\\pages\\Admin\\Sales\\quotes.vue' /* webpackChunkName: "pages/Admin/Sales/quotes" */))
const _52dec754 = () => interopDefault(import('..\\pages\\Admin\\Sales\\returns.vue' /* webpackChunkName: "pages/Admin/Sales/returns" */))
const _59ef2a2c = () => interopDefault(import('..\\pages\\Admin\\Sales\\shipments.vue' /* webpackChunkName: "pages/Admin/Sales/shipments" */))
const _45ffb814 = () => interopDefault(import('..\\pages\\Admin\\Sales\\transactions.vue' /* webpackChunkName: "pages/Admin/Sales/transactions" */))
const _78bafbaa = () => interopDefault(import('..\\pages\\Admin\\Shop\\attributes.vue' /* webpackChunkName: "pages/Admin/Shop/attributes" */))
const _1a7eadef = () => interopDefault(import('..\\pages\\Admin\\Shop\\categories.vue' /* webpackChunkName: "pages/Admin/Shop/categories" */))
const _a064cbc8 = () => interopDefault(import('..\\pages\\Admin\\Shop\\cities.vue' /* webpackChunkName: "pages/Admin/Shop/cities" */))
const _2ea96c5c = () => interopDefault(import('..\\pages\\Admin\\Shop\\collections.vue' /* webpackChunkName: "pages/Admin/Shop/collections" */))
const _4b99dcb1 = () => interopDefault(import('..\\pages\\Admin\\Shop\\countries.vue' /* webpackChunkName: "pages/Admin/Shop/countries" */))
const _7b2cafca = () => interopDefault(import('..\\pages\\Admin\\Shop\\coupons.vue' /* webpackChunkName: "pages/Admin/Shop/coupons" */))
const _f94a714e = () => interopDefault(import('..\\pages\\Admin\\Shop\\inventory.vue' /* webpackChunkName: "pages/Admin/Shop/inventory" */))
const _5c1fd7be = () => interopDefault(import('..\\pages\\Admin\\Shop\\partners.vue' /* webpackChunkName: "pages/Admin/Shop/partners" */))
const _2e56f3d0 = () => interopDefault(import('..\\pages\\Admin\\Shop\\product-types.vue' /* webpackChunkName: "pages/Admin/Shop/product-types" */))
const _e21c3012 = () => interopDefault(import('..\\pages\\Admin\\Shop\\products.vue' /* webpackChunkName: "pages/Admin/Shop/products" */))
const _6a4c543a = () => interopDefault(import('..\\pages\\Admin\\Shop\\shops.vue' /* webpackChunkName: "pages/Admin/Shop/shops" */))
const _38f8af56 = () => interopDefault(import('..\\pages\\Admin\\Shop\\states.vue' /* webpackChunkName: "pages/Admin/Shop/states" */))
const _37970d56 = () => interopDefault(import('..\\pages\\Admin\\Shop\\tax-rate.vue' /* webpackChunkName: "pages/Admin/Shop/tax-rate" */))
const _0eeb551e = () => interopDefault(import('..\\pages\\Admin\\Shop\\tax-rule.vue' /* webpackChunkName: "pages/Admin/Shop/tax-rule" */))
const _254b283a = () => interopDefault(import('..\\pages\\Admin\\Shop\\warehouses.vue' /* webpackChunkName: "pages/Admin/Shop/warehouses" */))
const _7ee73ee0 = () => interopDefault(import('..\\pages\\Admin\\System\\export-management.vue' /* webpackChunkName: "pages/Admin/System/export-management" */))
const _81ef6398 = () => interopDefault(import('..\\pages\\Admin\\System\\general-settings.vue' /* webpackChunkName: "pages/Admin/System/general-settings" */))
const _35767b8d = () => interopDefault(import('..\\pages\\Admin\\System\\help.vue' /* webpackChunkName: "pages/Admin/System/help" */))
const _85524262 = () => interopDefault(import('..\\pages\\Admin\\System\\import-management.vue' /* webpackChunkName: "pages/Admin/System/import-management" */))
const _0ea25e6b = () => interopDefault(import('..\\pages\\Admin\\System\\integrations.vue' /* webpackChunkName: "pages/Admin/System/integrations" */))
const _4304a89a = () => interopDefault(import('..\\pages\\Admin\\System\\knowledgebase.vue' /* webpackChunkName: "pages/Admin/System/knowledgebase" */))
const _31b9c322 = () => interopDefault(import('..\\pages\\Admin\\System\\role-manager.vue' /* webpackChunkName: "pages/Admin/System/role-manager" */))
const _5ba22522 = () => interopDefault(import('..\\pages\\Admin\\System\\settings.vue' /* webpackChunkName: "pages/Admin/System/settings" */))
const _0f36f970 = () => interopDefault(import('..\\pages\\Admin\\Customers\\customer\\newcustomer.vue' /* webpackChunkName: "pages/Admin/Customers/customer/newcustomer" */))
const _77c037a6 = () => interopDefault(import('..\\pages\\Admin\\Edit\\providers\\id.vue' /* webpackChunkName: "pages/Admin/Edit/providers/id" */))
const _d2581622 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\Email\\email-designer.vue' /* webpackChunkName: "pages/Admin/Marketing/Email/email-designer" */))
const _3e76ee18 = () => interopDefault(import('..\\pages\\Admin\\Shop\\Product\\Edit\\_id.vue' /* webpackChunkName: "pages/Admin/Shop/Product/Edit/_id" */))
const _b0633852 = () => interopDefault(import('..\\pages\\Admin\\Edit\\agreement\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/agreement/_id" */))
const _6d2fda2b = () => interopDefault(import('..\\pages\\Admin\\Edit\\article\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/article/_id" */))
const _03b58f85 = () => interopDefault(import('..\\pages\\Admin\\Edit\\attribute\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/attribute/_id" */))
const _528ada3e = () => interopDefault(import('..\\pages\\Admin\\Edit\\cases\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/cases/_id" */))
const _27c6d7e5 = () => interopDefault(import('..\\pages\\Admin\\Edit\\category\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/category/_id" */))
const _f9842e84 = () => interopDefault(import('..\\pages\\Admin\\Edit\\channel\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/channel/_id" */))
const _852a988a = () => interopDefault(import('..\\pages\\Admin\\Edit\\checklist\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/checklist/_id" */))
const _79a3f698 = () => interopDefault(import('..\\pages\\Admin\\Edit\\city\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/city/_id" */))
const _60e02a05 = () => interopDefault(import('..\\pages\\Admin\\Edit\\collection\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/collection/_id" */))
const _37a33e20 = () => interopDefault(import('..\\pages\\Admin\\Edit\\contracts\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/contracts/_id" */))
const _79d978ea = () => interopDefault(import('..\\pages\\Admin\\Edit\\country\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/country/_id" */))
const _26ef69fd = () => interopDefault(import('..\\pages\\Admin\\Edit\\coupon\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/coupon/_id" */))
const _24cb2b9c = () => interopDefault(import('..\\pages\\Admin\\Edit\\currency\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/currency/_id" */))
const _c6295240 = () => interopDefault(import('..\\pages\\Admin\\Edit\\customergroup\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/customergroup/_id" */))
const _66b4d00c = () => interopDefault(import('..\\pages\\Admin\\Edit\\deep-dive\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/deep-dive/_id" */))
const _4576f946 = () => interopDefault(import('..\\pages\\Admin\\Edit\\email_template\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/email_template/_id" */))
const _6ba2a4c7 = () => interopDefault(import('..\\pages\\Admin\\Edit\\event\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/event/_id" */))
const _426d9fb3 = () => interopDefault(import('..\\pages\\Admin\\Edit\\fullfillment\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/fullfillment/_id" */))
const _75d0eae9 = () => interopDefault(import('..\\pages\\Admin\\Edit\\gift-certificate\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/gift-certificate/_id" */))
const _76f80ec5 = () => interopDefault(import('..\\pages\\Admin\\Edit\\glossary\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/glossary/_id" */))
const _5f3e71d4 = () => interopDefault(import('..\\pages\\Admin\\Edit\\invoice\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/invoice/_id" */))
const _1c6c189c = () => interopDefault(import('..\\pages\\Admin\\Edit\\knowledgebase\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/knowledgebase/_id" */))
const _43fe912c = () => interopDefault(import('..\\pages\\Admin\\Edit\\leads\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/leads/_id" */))
const _97eb0af4 = () => interopDefault(import('..\\pages\\Admin\\Edit\\meeting\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/meeting/_id" */))
const _8d44fb6c = () => interopDefault(import('..\\pages\\Admin\\Edit\\newsletter\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/newsletter/_id" */))
const _8a3d163c = () => interopDefault(import('..\\pages\\Admin\\Edit\\newslettersubscriber\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/newslettersubscriber/_id" */))
const _4b13b9a8 = () => interopDefault(import('..\\pages\\Admin\\Edit\\ooto\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/ooto/_id" */))
const _262db390 = () => interopDefault(import('..\\pages\\Admin\\Edit\\opportunities\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/opportunities/_id" */))
const _99379418 = () => interopDefault(import('..\\pages\\Admin\\Edit\\page\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/page/_id" */))
const _59a912ce = () => interopDefault(import('..\\pages\\Admin\\Edit\\partner\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/partner/_id" */))
const _755b655c = () => interopDefault(import('..\\pages\\Admin\\Edit\\pdf_template\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/pdf_template/_id" */))
const _1e99af6a = () => interopDefault(import('..\\pages\\Admin\\Edit\\product-type\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/product-type/_id" */))
const _3198c252 = () => interopDefault(import('..\\pages\\Admin\\Edit\\product\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/product/_id" */))
const _19d9a7e9 = () => interopDefault(import('..\\pages\\Admin\\Edit\\projects\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/projects/_id" */))
const _4f52c868 = () => interopDefault(import('..\\pages\\Admin\\Edit\\quotes\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/quotes/_id" */))
const _6046bcaf = () => interopDefault(import('..\\pages\\Admin\\Edit\\report\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/report/_id" */))
const _e277df9a = () => interopDefault(import('..\\pages\\Admin\\Edit\\return\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/return/_id" */))
const _166e430b = () => interopDefault(import('..\\pages\\Admin\\Edit\\review\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/review/_id" */))
const _358dcd14 = () => interopDefault(import('..\\pages\\Admin\\Edit\\reward\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/reward/_id" */))
const _f6df86e4 = () => interopDefault(import('..\\pages\\Admin\\Edit\\segment\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/segment/_id" */))
const _669b92c9 = () => interopDefault(import('..\\pages\\Admin\\Edit\\shipment\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/shipment/_id" */))
const _3d09ba84 = () => interopDefault(import('..\\pages\\Admin\\Edit\\shops\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/shops/_id" */))
const _11f4cea0 = () => interopDefault(import('..\\pages\\Admin\\Edit\\state\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/state/_id" */))
const _d56980f2 = () => interopDefault(import('..\\pages\\Admin\\Edit\\tag\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/tag/_id" */))
const _c73b8e1c = () => interopDefault(import('..\\pages\\Admin\\Edit\\target\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/target/_id" */))
const _60bd235a = () => interopDefault(import('..\\pages\\Admin\\Edit\\tasks\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/tasks/_id" */))
const _95742094 = () => interopDefault(import('..\\pages\\Admin\\Edit\\taxrate\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/taxrate/_id" */))
const _affd75cc = () => interopDefault(import('..\\pages\\Admin\\Edit\\taxrule\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/taxrule/_id" */))
const _5f2c8c52 = () => interopDefault(import('..\\pages\\Admin\\Edit\\ticket\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/ticket/_id" */))
const _5c157d94 = () => interopDefault(import('..\\pages\\Admin\\Edit\\visit\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/visit/_id" */))
const _3e403b3e = () => interopDefault(import('..\\pages\\Admin\\Edit\\warehouse\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/warehouse/_id" */))
const _fb0b3512 = () => interopDefault(import('..\\pages\\Admin\\Edit\\zone\\_id.vue' /* webpackChunkName: "pages/Admin/Edit/zone/_id" */))
const _2f2cdfd7 = () => interopDefault(import('..\\pages\\Admin\\Marketing\\Email\\_id.vue' /* webpackChunkName: "pages/Admin/Marketing/Email/_id" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/es",
    component: _8c3791c0,
    name: "index___es"
  }, {
    path: "/fr",
    component: _8c3791c0,
    name: "index___fr"
  }, {
    path: "/search",
    component: _2e61864a,
    name: "search___en"
  }, {
    path: "/test",
    component: _708cdab4,
    name: "test___en"
  }, {
    path: "/Auth/Forgot",
    component: _e181e7a6,
    name: "Auth-Forgot___en"
  }, {
    path: "/Auth/Login",
    component: _1d818162,
    name: "Auth-Login___en"
  }, {
    path: "/Auth/Register",
    component: _250d39a6,
    name: "Auth-Register___en"
  }, {
    path: "/Auth/Reset",
    component: _5f4beb96,
    name: "Auth-Reset___en"
  }, {
    path: "/es/search",
    component: _2e61864a,
    name: "search___es"
  }, {
    path: "/es/test",
    component: _708cdab4,
    name: "test___es"
  }, {
    path: "/fr/search",
    component: _2e61864a,
    name: "search___fr"
  }, {
    path: "/fr/test",
    component: _708cdab4,
    name: "test___fr"
  }, {
    path: "/User/my-account",
    component: _beb522ce,
    name: "User-my-account___en"
  }, {
    path: "/Admin/Add-New/add-new-agreement",
    component: _1bc74b8c,
    name: "Admin-Add-New-add-new-agreement___en"
  }, {
    path: "/Admin/Add-New/add-new-article",
    component: _5cc64526,
    name: "Admin-Add-New-add-new-article___en"
  }, {
    path: "/Admin/Add-New/add-new-attribute",
    component: _19d819cc,
    name: "Admin-Add-New-add-new-attribute___en"
  }, {
    path: "/Admin/Add-New/add-new-campaign",
    component: _606c8e10,
    name: "Admin-Add-New-add-new-campaign___en"
  }, {
    path: "/Admin/Add-New/add-new-case",
    component: _28496c30,
    name: "Admin-Add-New-add-new-case___en"
  }, {
    path: "/Admin/Add-New/add-new-category",
    component: _6f8aa2fe,
    name: "Admin-Add-New-add-new-category___en"
  }, {
    path: "/Admin/Add-New/add-new-channel",
    component: _3c5826b3,
    name: "Admin-Add-New-add-new-channel___en"
  }, {
    path: "/Admin/Add-New/add-new-checklist",
    component: _4c7eabd6,
    name: "Admin-Add-New-add-new-checklist___en"
  }, {
    path: "/Admin/Add-New/add-new-city",
    component: _5b6c162a,
    name: "Admin-Add-New-add-new-city___en"
  }, {
    path: "/Admin/Add-New/add-new-collection",
    component: _a9866ac4,
    name: "Admin-Add-New-add-new-collection___en"
  }, {
    path: "/Admin/Add-New/add-new-contract",
    component: _028ccd12,
    name: "Admin-Add-New-add-new-contract___en"
  }, {
    path: "/Admin/Add-New/add-new-country",
    component: _58030074,
    name: "Admin-Add-New-add-new-country___en"
  }, {
    path: "/Admin/Add-New/add-new-coupon",
    component: _494337b4,
    name: "Admin-Add-New-add-new-coupon___en"
  }, {
    path: "/Admin/Add-New/add-new-currency",
    component: _dbe3d6de,
    name: "Admin-Add-New-add-new-currency___en"
  }, {
    path: "/Admin/Add-New/add-new-customer",
    component: _e8661444,
    name: "Admin-Add-New-add-new-customer___en"
  }, {
    path: "/Admin/Add-New/add-new-customergroup",
    component: _6c8dabde,
    name: "Admin-Add-New-add-new-customergroup___en"
  }, {
    path: "/Admin/Add-New/add-new-deepdive",
    component: _6a22d9e0,
    name: "Admin-Add-New-add-new-deepdive___en"
  }, {
    path: "/Admin/Add-New/add-new-email",
    component: _39e746cc,
    name: "Admin-Add-New-add-new-email___en"
  }, {
    path: "/Admin/Add-New/add-new-emailtemplates",
    component: _4a7fd0c6,
    name: "Admin-Add-New-add-new-emailtemplates___en"
  }, {
    path: "/Admin/Add-New/add-new-eosr",
    component: _454b95ee,
    name: "Admin-Add-New-add-new-eosr___en"
  }, {
    path: "/Admin/Add-New/add-new-event",
    component: _8538826c,
    name: "Admin-Add-New-add-new-event___en"
  }, {
    path: "/Admin/Add-New/add-new-fullfilment",
    component: _53db7ea8,
    name: "Admin-Add-New-add-new-fullfilment___en"
  }, {
    path: "/Admin/Add-New/add-new-gift-certificates",
    component: _a484482e,
    name: "Admin-Add-New-add-new-gift-certificates___en"
  }, {
    path: "/Admin/Add-New/add-new-glossary",
    component: _446aa01e,
    name: "Admin-Add-New-add-new-glossary___en"
  }, {
    path: "/Admin/Add-New/add-new-invoice",
    component: _0ec07046,
    name: "Admin-Add-New-add-new-invoice___en"
  }, {
    path: "/Admin/Add-New/add-new-knowledgebase",
    component: _94475c02,
    name: "Admin-Add-New-add-new-knowledgebase___en"
  }, {
    path: "/Admin/Add-New/add-new-lead",
    component: _f7f0cb48,
    name: "Admin-Add-New-add-new-lead___en"
  }, {
    path: "/Admin/Add-New/add-new-meeting",
    component: _114cd02a,
    name: "Admin-Add-New-add-new-meeting___en"
  }, {
    path: "/Admin/Add-New/add-new-newsletter",
    component: _fdbec98e,
    name: "Admin-Add-New-add-new-newsletter___en"
  }, {
    path: "/Admin/Add-New/add-new-newslettersubscriber%20copy",
    component: _95ec6cf8,
    name: "Admin-Add-New-add-new-newslettersubscriber copy___en"
  }, {
    path: "/Admin/Add-New/add-new-ooto",
    component: _249ef04a,
    name: "Admin-Add-New-add-new-ooto___en"
  }, {
    path: "/Admin/Add-New/add-new-opportunity",
    component: _4ab7c6fa,
    name: "Admin-Add-New-add-new-opportunity___en"
  }, {
    path: "/Admin/Add-New/add-new-page",
    component: _5a3e8c0f,
    name: "Admin-Add-New-add-new-page___en"
  }, {
    path: "/Admin/Add-New/add-new-partner",
    component: _661a1bf8,
    name: "Admin-Add-New-add-new-partner___en"
  }, {
    path: "/Admin/Add-New/add-new-pdftemplates",
    component: _39508807,
    name: "Admin-Add-New-add-new-pdftemplates___en"
  }, {
    path: "/Admin/Add-New/add-new-product",
    component: _59cebec2,
    name: "Admin-Add-New-add-new-product___en"
  }, {
    path: "/Admin/Add-New/add-new-producttype",
    component: _5c5ca759,
    name: "Admin-Add-New-add-new-producttype___en"
  }, {
    path: "/Admin/Add-New/add-new-project",
    component: _18080c6e,
    name: "Admin-Add-New-add-new-project___en"
  }, {
    path: "/Admin/Add-New/add-new-quote",
    component: _631fc9ac,
    name: "Admin-Add-New-add-new-quote___en"
  }, {
    path: "/Admin/Add-New/add-new-report",
    component: _2a26aa34,
    name: "Admin-Add-New-add-new-report___en"
  }, {
    path: "/Admin/Add-New/add-new-return",
    component: _06bc3430,
    name: "Admin-Add-New-add-new-return___en"
  }, {
    path: "/Admin/Add-New/add-new-review",
    component: _46039a58,
    name: "Admin-Add-New-add-new-review___en"
  }, {
    path: "/Admin/Add-New/add-new-rewards",
    component: _629b4854,
    name: "Admin-Add-New-add-new-rewards___en"
  }, {
    path: "/Admin/Add-New/add-new-role",
    component: _17205e76,
    name: "Admin-Add-New-add-new-role___en"
  }, {
    path: "/Admin/Add-New/add-new-schedule",
    component: _c92ff7d2,
    name: "Admin-Add-New-add-new-schedule___en"
  }, {
    path: "/Admin/Add-New/add-new-segment",
    component: _19969e3a,
    name: "Admin-Add-New-add-new-segment___en"
  }, {
    path: "/Admin/Add-New/add-new-shipment",
    component: _33dda99a,
    name: "Admin-Add-New-add-new-shipment___en"
  }, {
    path: "/Admin/Add-New/add-new-shop",
    component: _126f78f6,
    name: "Admin-Add-New-add-new-shop___en"
  }, {
    path: "/Admin/Add-New/add-new-staffmembers",
    component: _eec3328e,
    name: "Admin-Add-New-add-new-staffmembers___en"
  }, {
    path: "/Admin/Add-New/add-new-state",
    component: _3f303d41,
    name: "Admin-Add-New-add-new-state___en"
  }, {
    path: "/Admin/Add-New/add-new-survey",
    component: _e2470d4c,
    name: "Admin-Add-New-add-new-survey___en"
  }, {
    path: "/Admin/Add-New/add-new-tag",
    component: _62cd51ca,
    name: "Admin-Add-New-add-new-tag___en"
  }, {
    path: "/Admin/Add-New/add-new-target",
    component: _57ed5fde,
    name: "Admin-Add-New-add-new-target___en"
  }, {
    path: "/Admin/Add-New/add-new-task",
    component: _0e91f405,
    name: "Admin-Add-New-add-new-task___en"
  }, {
    path: "/Admin/Add-New/add-new-taxrate",
    component: _6694b68a,
    name: "Admin-Add-New-add-new-taxrate___en"
  }, {
    path: "/Admin/Add-New/add-new-taxrule",
    component: _3de8fe52,
    name: "Admin-Add-New-add-new-taxrule___en"
  }, {
    path: "/Admin/Add-New/add-new-ticket",
    component: _3394140c,
    name: "Admin-Add-New-add-new-ticket___en"
  }, {
    path: "/Admin/Add-New/add-new-visit",
    component: _2b8ed8fb,
    name: "Admin-Add-New-add-new-visit___en"
  }, {
    path: "/Admin/Add-New/add-new-warehouse",
    component: _25dd3e73,
    name: "Admin-Add-New-add-new-warehouse___en"
  }, {
    path: "/Admin/Add-New/add-new-zone",
    component: _599376ac,
    name: "Admin-Add-New-add-new-zone___en"
  }, {
    path: "/Admin/Content/blog",
    component: _9d529964,
    name: "Admin-Content-blog___en"
  }, {
    path: "/Admin/Content/glossary",
    component: _98c3f46c,
    name: "Admin-Content-glossary___en"
  }, {
    path: "/Admin/Content/media-manager",
    component: _52b993c8,
    name: "Admin-Content-media-manager___en"
  }, {
    path: "/Admin/Content/pages",
    component: _77a0f0c8,
    name: "Admin-Content-pages___en"
  }, {
    path: "/Admin/Content/projects",
    component: _033b73b4,
    name: "Admin-Content-projects___en"
  }, {
    path: "/Admin/Content/tags",
    component: _a76cb776,
    name: "Admin-Content-tags___en"
  }, {
    path: "/Admin/Customers/all-customers",
    component: _721d0311,
    name: "Admin-Customers-all-customers___en"
  }, {
    path: "/Admin/Customers/leads",
    component: _47c4b57f,
    name: "Admin-Customers-leads___en"
  }, {
    path: "/Admin/Customers/meetings",
    component: _1b5b8f40,
    name: "Admin-Customers-meetings___en"
  }, {
    path: "/Admin/Customers/online-customers",
    component: _4c8afaa3,
    name: "Admin-Customers-online-customers___en"
  }, {
    path: "/Admin/Customers/opportunities",
    component: _fd636ace,
    name: "Admin-Customers-opportunities___en"
  }, {
    path: "/Admin/Customers/segments",
    component: _71da3e68,
    name: "Admin-Customers-segments___en"
  }, {
    path: "/Admin/Customers/social-groups",
    component: _2109ea9c,
    name: "Admin-Customers-social-groups___en"
  }, {
    path: "/Admin/Customers/tasks",
    component: _0e8590f6,
    name: "Admin-Customers-tasks___en"
  }, {
    path: "/Admin/Marketing/checklists",
    component: _6c07dba6,
    name: "Admin-Marketing-checklists___en"
  }, {
    path: "/Admin/Marketing/communications",
    component: _334552f6,
    name: "Admin-Marketing-communications___en"
  }, {
    path: "/Admin/Marketing/contracts",
    component: _d40a98d0,
    name: "Admin-Marketing-contracts___en"
  }, {
    path: "/Admin/Marketing/events",
    component: _1416489c,
    name: "Admin-Marketing-events___en"
  }, {
    path: "/Admin/Marketing/invitations",
    component: _7fd3cdb1,
    name: "Admin-Marketing-invitations___en"
  }, {
    path: "/Admin/Marketing/newsletter",
    component: _b3b3f25c,
    name: "Admin-Marketing-newsletter___en"
  }, {
    path: "/Admin/Marketing/reviews",
    component: _3ceb965c,
    name: "Admin-Marketing-reviews___en"
  }, {
    path: "/Admin/Marketing/rewards",
    component: _73eba94a,
    name: "Admin-Marketing-rewards___en"
  }, {
    path: "/Admin/Marketing/seo",
    component: _311ab394,
    name: "Admin-Marketing-seo___en"
  }, {
    path: "/Admin/Marketing/ticketing",
    component: _ba50fe66,
    name: "Admin-Marketing-ticketing___en"
  }, {
    path: "/Admin/Marketing/training",
    component: _bcf7c29a,
    name: "Admin-Marketing-training___en"
  }, {
    path: "/Admin/Marketing/visits",
    component: _4d2d07a1,
    name: "Admin-Marketing-visits___en"
  }, {
    path: "/Admin/Reports/calendars",
    component: _ebc5751a,
    name: "Admin-Reports-calendars___en"
  }, {
    path: "/Admin/Reports/cases",
    component: _5b4be07e,
    name: "Admin-Reports-cases___en"
  }, {
    path: "/Admin/Reports/deep-dive",
    component: _0c2d9eb3,
    name: "Admin-Reports-deep-dive___en"
  }, {
    path: "/Admin/Reports/eosr",
    component: _79ab0e7b,
    name: "Admin-Reports-eosr___en"
  }, {
    path: "/Admin/Reports/ooto",
    component: _ebfd3d66,
    name: "Admin-Reports-ooto___en"
  }, {
    path: "/Admin/Reports/reports",
    component: _7a3ad286,
    name: "Admin-Reports-reports___en"
  }, {
    path: "/Admin/Reports/statistics",
    component: _c71502d6,
    name: "Admin-Reports-statistics___en"
  }, {
    path: "/Admin/Reports/surveys",
    component: _1632a752,
    name: "Admin-Reports-surveys___en"
  }, {
    path: "/Admin/Reports/team-scheduler",
    component: _879bdc86,
    name: "Admin-Reports-team-scheduler___en"
  }, {
    path: "/Admin/Sales/agreements",
    component: _83855bb0,
    name: "Admin-Sales-agreements___en"
  }, {
    path: "/Admin/Sales/certificates",
    component: _ee72d60a,
    name: "Admin-Sales-certificates___en"
  }, {
    path: "/Admin/Sales/credit-memos",
    component: _b68f0d38,
    name: "Admin-Sales-credit-memos___en"
  }, {
    path: "/Admin/Sales/invoices",
    component: _6db68ca5,
    name: "Admin-Sales-invoices___en"
  }, {
    path: "/Admin/Sales/orders",
    component: _441412e4,
    name: "Admin-Sales-orders___en"
  }, {
    path: "/Admin/Sales/quotes",
    component: _636fa876,
    name: "Admin-Sales-quotes___en"
  }, {
    path: "/Admin/Sales/returns",
    component: _52dec754,
    name: "Admin-Sales-returns___en"
  }, {
    path: "/Admin/Sales/shipments",
    component: _59ef2a2c,
    name: "Admin-Sales-shipments___en"
  }, {
    path: "/Admin/Sales/transactions",
    component: _45ffb814,
    name: "Admin-Sales-transactions___en"
  }, {
    path: "/Admin/Shop/attributes",
    component: _78bafbaa,
    name: "Admin-Shop-attributes___en"
  }, {
    path: "/Admin/Shop/categories",
    component: _1a7eadef,
    name: "Admin-Shop-categories___en"
  }, {
    path: "/Admin/Shop/cities",
    component: _a064cbc8,
    name: "Admin-Shop-cities___en"
  }, {
    path: "/Admin/Shop/collections",
    component: _2ea96c5c,
    name: "Admin-Shop-collections___en"
  }, {
    path: "/Admin/Shop/countries",
    component: _4b99dcb1,
    name: "Admin-Shop-countries___en"
  }, {
    path: "/Admin/Shop/coupons",
    component: _7b2cafca,
    name: "Admin-Shop-coupons___en"
  }, {
    path: "/Admin/Shop/inventory",
    component: _f94a714e,
    name: "Admin-Shop-inventory___en"
  }, {
    path: "/Admin/Shop/partners",
    component: _5c1fd7be,
    name: "Admin-Shop-partners___en"
  }, {
    path: "/Admin/Shop/product-types",
    component: _2e56f3d0,
    name: "Admin-Shop-product-types___en"
  }, {
    path: "/Admin/Shop/products",
    component: _e21c3012,
    name: "Admin-Shop-products___en"
  }, {
    path: "/Admin/Shop/shops",
    component: _6a4c543a,
    name: "Admin-Shop-shops___en"
  }, {
    path: "/Admin/Shop/states",
    component: _38f8af56,
    name: "Admin-Shop-states___en"
  }, {
    path: "/Admin/Shop/tax-rate",
    component: _37970d56,
    name: "Admin-Shop-tax-rate___en"
  }, {
    path: "/Admin/Shop/tax-rule",
    component: _0eeb551e,
    name: "Admin-Shop-tax-rule___en"
  }, {
    path: "/Admin/Shop/warehouses",
    component: _254b283a,
    name: "Admin-Shop-warehouses___en"
  }, {
    path: "/Admin/System/export-management",
    component: _7ee73ee0,
    name: "Admin-System-export-management___en"
  }, {
    path: "/Admin/System/general-settings",
    component: _81ef6398,
    name: "Admin-System-general-settings___en"
  }, {
    path: "/Admin/System/help",
    component: _35767b8d,
    name: "Admin-System-help___en"
  }, {
    path: "/Admin/System/import-management",
    component: _85524262,
    name: "Admin-System-import-management___en"
  }, {
    path: "/Admin/System/integrations",
    component: _0ea25e6b,
    name: "Admin-System-integrations___en"
  }, {
    path: "/Admin/System/knowledgebase",
    component: _4304a89a,
    name: "Admin-System-knowledgebase___en"
  }, {
    path: "/Admin/System/role-manager",
    component: _31b9c322,
    name: "Admin-System-role-manager___en"
  }, {
    path: "/Admin/System/settings",
    component: _5ba22522,
    name: "Admin-System-settings___en"
  }, {
    path: "/es/Auth/Forgot",
    component: _e181e7a6,
    name: "Auth-Forgot___es"
  }, {
    path: "/es/Auth/Login",
    component: _1d818162,
    name: "Auth-Login___es"
  }, {
    path: "/es/Auth/Register",
    component: _250d39a6,
    name: "Auth-Register___es"
  }, {
    path: "/es/Auth/Reset",
    component: _5f4beb96,
    name: "Auth-Reset___es"
  }, {
    path: "/es/User/my-account",
    component: _beb522ce,
    name: "User-my-account___es"
  }, {
    path: "/fr/Auth/Forgot",
    component: _e181e7a6,
    name: "Auth-Forgot___fr"
  }, {
    path: "/fr/Auth/Login",
    component: _1d818162,
    name: "Auth-Login___fr"
  }, {
    path: "/fr/Auth/Register",
    component: _250d39a6,
    name: "Auth-Register___fr"
  }, {
    path: "/fr/Auth/Reset",
    component: _5f4beb96,
    name: "Auth-Reset___fr"
  }, {
    path: "/fr/User/my-account",
    component: _beb522ce,
    name: "User-my-account___fr"
  }, {
    path: "/Admin/Customers/customer/newcustomer",
    component: _0f36f970,
    name: "Admin-Customers-customer-newcustomer___en"
  }, {
    path: "/Admin/Edit/providers/id",
    component: _77c037a6,
    name: "Admin-Edit-providers-id___en"
  }, {
    path: "/Admin/Marketing/Email/email-designer",
    component: _d2581622,
    name: "Admin-Marketing-Email-email-designer___en"
  }, {
    path: "/es/Admin/Add-New/add-new-agreement",
    component: _1bc74b8c,
    name: "Admin-Add-New-add-new-agreement___es"
  }, {
    path: "/es/Admin/Add-New/add-new-article",
    component: _5cc64526,
    name: "Admin-Add-New-add-new-article___es"
  }, {
    path: "/es/Admin/Add-New/add-new-attribute",
    component: _19d819cc,
    name: "Admin-Add-New-add-new-attribute___es"
  }, {
    path: "/es/Admin/Add-New/add-new-campaign",
    component: _606c8e10,
    name: "Admin-Add-New-add-new-campaign___es"
  }, {
    path: "/es/Admin/Add-New/add-new-case",
    component: _28496c30,
    name: "Admin-Add-New-add-new-case___es"
  }, {
    path: "/es/Admin/Add-New/add-new-category",
    component: _6f8aa2fe,
    name: "Admin-Add-New-add-new-category___es"
  }, {
    path: "/es/Admin/Add-New/add-new-channel",
    component: _3c5826b3,
    name: "Admin-Add-New-add-new-channel___es"
  }, {
    path: "/es/Admin/Add-New/add-new-checklist",
    component: _4c7eabd6,
    name: "Admin-Add-New-add-new-checklist___es"
  }, {
    path: "/es/Admin/Add-New/add-new-city",
    component: _5b6c162a,
    name: "Admin-Add-New-add-new-city___es"
  }, {
    path: "/es/Admin/Add-New/add-new-collection",
    component: _a9866ac4,
    name: "Admin-Add-New-add-new-collection___es"
  }, {
    path: "/es/Admin/Add-New/add-new-contract",
    component: _028ccd12,
    name: "Admin-Add-New-add-new-contract___es"
  }, {
    path: "/es/Admin/Add-New/add-new-country",
    component: _58030074,
    name: "Admin-Add-New-add-new-country___es"
  }, {
    path: "/es/Admin/Add-New/add-new-coupon",
    component: _494337b4,
    name: "Admin-Add-New-add-new-coupon___es"
  }, {
    path: "/es/Admin/Add-New/add-new-currency",
    component: _dbe3d6de,
    name: "Admin-Add-New-add-new-currency___es"
  }, {
    path: "/es/Admin/Add-New/add-new-customer",
    component: _e8661444,
    name: "Admin-Add-New-add-new-customer___es"
  }, {
    path: "/es/Admin/Add-New/add-new-customergroup",
    component: _6c8dabde,
    name: "Admin-Add-New-add-new-customergroup___es"
  }, {
    path: "/es/Admin/Add-New/add-new-deepdive",
    component: _6a22d9e0,
    name: "Admin-Add-New-add-new-deepdive___es"
  }, {
    path: "/es/Admin/Add-New/add-new-email",
    component: _39e746cc,
    name: "Admin-Add-New-add-new-email___es"
  }, {
    path: "/es/Admin/Add-New/add-new-emailtemplates",
    component: _4a7fd0c6,
    name: "Admin-Add-New-add-new-emailtemplates___es"
  }, {
    path: "/es/Admin/Add-New/add-new-eosr",
    component: _454b95ee,
    name: "Admin-Add-New-add-new-eosr___es"
  }, {
    path: "/es/Admin/Add-New/add-new-event",
    component: _8538826c,
    name: "Admin-Add-New-add-new-event___es"
  }, {
    path: "/es/Admin/Add-New/add-new-fullfilment",
    component: _53db7ea8,
    name: "Admin-Add-New-add-new-fullfilment___es"
  }, {
    path: "/es/Admin/Add-New/add-new-gift-certificates",
    component: _a484482e,
    name: "Admin-Add-New-add-new-gift-certificates___es"
  }, {
    path: "/es/Admin/Add-New/add-new-glossary",
    component: _446aa01e,
    name: "Admin-Add-New-add-new-glossary___es"
  }, {
    path: "/es/Admin/Add-New/add-new-invoice",
    component: _0ec07046,
    name: "Admin-Add-New-add-new-invoice___es"
  }, {
    path: "/es/Admin/Add-New/add-new-knowledgebase",
    component: _94475c02,
    name: "Admin-Add-New-add-new-knowledgebase___es"
  }, {
    path: "/es/Admin/Add-New/add-new-lead",
    component: _f7f0cb48,
    name: "Admin-Add-New-add-new-lead___es"
  }, {
    path: "/es/Admin/Add-New/add-new-meeting",
    component: _114cd02a,
    name: "Admin-Add-New-add-new-meeting___es"
  }, {
    path: "/es/Admin/Add-New/add-new-newsletter",
    component: _fdbec98e,
    name: "Admin-Add-New-add-new-newsletter___es"
  }, {
    path: "/es/Admin/Add-New/add-new-newslettersubscriber%20copy",
    component: _95ec6cf8,
    name: "Admin-Add-New-add-new-newslettersubscriber copy___es"
  }, {
    path: "/es/Admin/Add-New/add-new-ooto",
    component: _249ef04a,
    name: "Admin-Add-New-add-new-ooto___es"
  }, {
    path: "/es/Admin/Add-New/add-new-opportunity",
    component: _4ab7c6fa,
    name: "Admin-Add-New-add-new-opportunity___es"
  }, {
    path: "/es/Admin/Add-New/add-new-page",
    component: _5a3e8c0f,
    name: "Admin-Add-New-add-new-page___es"
  }, {
    path: "/es/Admin/Add-New/add-new-partner",
    component: _661a1bf8,
    name: "Admin-Add-New-add-new-partner___es"
  }, {
    path: "/es/Admin/Add-New/add-new-pdftemplates",
    component: _39508807,
    name: "Admin-Add-New-add-new-pdftemplates___es"
  }, {
    path: "/es/Admin/Add-New/add-new-product",
    component: _59cebec2,
    name: "Admin-Add-New-add-new-product___es"
  }, {
    path: "/es/Admin/Add-New/add-new-producttype",
    component: _5c5ca759,
    name: "Admin-Add-New-add-new-producttype___es"
  }, {
    path: "/es/Admin/Add-New/add-new-project",
    component: _18080c6e,
    name: "Admin-Add-New-add-new-project___es"
  }, {
    path: "/es/Admin/Add-New/add-new-quote",
    component: _631fc9ac,
    name: "Admin-Add-New-add-new-quote___es"
  }, {
    path: "/es/Admin/Add-New/add-new-report",
    component: _2a26aa34,
    name: "Admin-Add-New-add-new-report___es"
  }, {
    path: "/es/Admin/Add-New/add-new-return",
    component: _06bc3430,
    name: "Admin-Add-New-add-new-return___es"
  }, {
    path: "/es/Admin/Add-New/add-new-review",
    component: _46039a58,
    name: "Admin-Add-New-add-new-review___es"
  }, {
    path: "/es/Admin/Add-New/add-new-rewards",
    component: _629b4854,
    name: "Admin-Add-New-add-new-rewards___es"
  }, {
    path: "/es/Admin/Add-New/add-new-role",
    component: _17205e76,
    name: "Admin-Add-New-add-new-role___es"
  }, {
    path: "/es/Admin/Add-New/add-new-schedule",
    component: _c92ff7d2,
    name: "Admin-Add-New-add-new-schedule___es"
  }, {
    path: "/es/Admin/Add-New/add-new-segment",
    component: _19969e3a,
    name: "Admin-Add-New-add-new-segment___es"
  }, {
    path: "/es/Admin/Add-New/add-new-shipment",
    component: _33dda99a,
    name: "Admin-Add-New-add-new-shipment___es"
  }, {
    path: "/es/Admin/Add-New/add-new-shop",
    component: _126f78f6,
    name: "Admin-Add-New-add-new-shop___es"
  }, {
    path: "/es/Admin/Add-New/add-new-staffmembers",
    component: _eec3328e,
    name: "Admin-Add-New-add-new-staffmembers___es"
  }, {
    path: "/es/Admin/Add-New/add-new-state",
    component: _3f303d41,
    name: "Admin-Add-New-add-new-state___es"
  }, {
    path: "/es/Admin/Add-New/add-new-survey",
    component: _e2470d4c,
    name: "Admin-Add-New-add-new-survey___es"
  }, {
    path: "/es/Admin/Add-New/add-new-tag",
    component: _62cd51ca,
    name: "Admin-Add-New-add-new-tag___es"
  }, {
    path: "/es/Admin/Add-New/add-new-target",
    component: _57ed5fde,
    name: "Admin-Add-New-add-new-target___es"
  }, {
    path: "/es/Admin/Add-New/add-new-task",
    component: _0e91f405,
    name: "Admin-Add-New-add-new-task___es"
  }, {
    path: "/es/Admin/Add-New/add-new-taxrate",
    component: _6694b68a,
    name: "Admin-Add-New-add-new-taxrate___es"
  }, {
    path: "/es/Admin/Add-New/add-new-taxrule",
    component: _3de8fe52,
    name: "Admin-Add-New-add-new-taxrule___es"
  }, {
    path: "/es/Admin/Add-New/add-new-ticket",
    component: _3394140c,
    name: "Admin-Add-New-add-new-ticket___es"
  }, {
    path: "/es/Admin/Add-New/add-new-visit",
    component: _2b8ed8fb,
    name: "Admin-Add-New-add-new-visit___es"
  }, {
    path: "/es/Admin/Add-New/add-new-warehouse",
    component: _25dd3e73,
    name: "Admin-Add-New-add-new-warehouse___es"
  }, {
    path: "/es/Admin/Add-New/add-new-zone",
    component: _599376ac,
    name: "Admin-Add-New-add-new-zone___es"
  }, {
    path: "/es/Admin/Content/blog",
    component: _9d529964,
    name: "Admin-Content-blog___es"
  }, {
    path: "/es/Admin/Content/glossary",
    component: _98c3f46c,
    name: "Admin-Content-glossary___es"
  }, {
    path: "/es/Admin/Content/media-manager",
    component: _52b993c8,
    name: "Admin-Content-media-manager___es"
  }, {
    path: "/es/Admin/Content/pages",
    component: _77a0f0c8,
    name: "Admin-Content-pages___es"
  }, {
    path: "/es/Admin/Content/projects",
    component: _033b73b4,
    name: "Admin-Content-projects___es"
  }, {
    path: "/es/Admin/Content/tags",
    component: _a76cb776,
    name: "Admin-Content-tags___es"
  }, {
    path: "/es/Admin/Customers/all-customers",
    component: _721d0311,
    name: "Admin-Customers-all-customers___es"
  }, {
    path: "/es/Admin/Customers/leads",
    component: _47c4b57f,
    name: "Admin-Customers-leads___es"
  }, {
    path: "/es/Admin/Customers/meetings",
    component: _1b5b8f40,
    name: "Admin-Customers-meetings___es"
  }, {
    path: "/es/Admin/Customers/online-customers",
    component: _4c8afaa3,
    name: "Admin-Customers-online-customers___es"
  }, {
    path: "/es/Admin/Customers/opportunities",
    component: _fd636ace,
    name: "Admin-Customers-opportunities___es"
  }, {
    path: "/es/Admin/Customers/segments",
    component: _71da3e68,
    name: "Admin-Customers-segments___es"
  }, {
    path: "/es/Admin/Customers/social-groups",
    component: _2109ea9c,
    name: "Admin-Customers-social-groups___es"
  }, {
    path: "/es/Admin/Customers/tasks",
    component: _0e8590f6,
    name: "Admin-Customers-tasks___es"
  }, {
    path: "/es/Admin/Marketing/checklists",
    component: _6c07dba6,
    name: "Admin-Marketing-checklists___es"
  }, {
    path: "/es/Admin/Marketing/communications",
    component: _334552f6,
    name: "Admin-Marketing-communications___es"
  }, {
    path: "/es/Admin/Marketing/contracts",
    component: _d40a98d0,
    name: "Admin-Marketing-contracts___es"
  }, {
    path: "/es/Admin/Marketing/events",
    component: _1416489c,
    name: "Admin-Marketing-events___es"
  }, {
    path: "/es/Admin/Marketing/invitations",
    component: _7fd3cdb1,
    name: "Admin-Marketing-invitations___es"
  }, {
    path: "/es/Admin/Marketing/newsletter",
    component: _b3b3f25c,
    name: "Admin-Marketing-newsletter___es"
  }, {
    path: "/es/Admin/Marketing/reviews",
    component: _3ceb965c,
    name: "Admin-Marketing-reviews___es"
  }, {
    path: "/es/Admin/Marketing/rewards",
    component: _73eba94a,
    name: "Admin-Marketing-rewards___es"
  }, {
    path: "/es/Admin/Marketing/seo",
    component: _311ab394,
    name: "Admin-Marketing-seo___es"
  }, {
    path: "/es/Admin/Marketing/ticketing",
    component: _ba50fe66,
    name: "Admin-Marketing-ticketing___es"
  }, {
    path: "/es/Admin/Marketing/training",
    component: _bcf7c29a,
    name: "Admin-Marketing-training___es"
  }, {
    path: "/es/Admin/Marketing/visits",
    component: _4d2d07a1,
    name: "Admin-Marketing-visits___es"
  }, {
    path: "/es/Admin/Reports/calendars",
    component: _ebc5751a,
    name: "Admin-Reports-calendars___es"
  }, {
    path: "/es/Admin/Reports/cases",
    component: _5b4be07e,
    name: "Admin-Reports-cases___es"
  }, {
    path: "/es/Admin/Reports/deep-dive",
    component: _0c2d9eb3,
    name: "Admin-Reports-deep-dive___es"
  }, {
    path: "/es/Admin/Reports/eosr",
    component: _79ab0e7b,
    name: "Admin-Reports-eosr___es"
  }, {
    path: "/es/Admin/Reports/ooto",
    component: _ebfd3d66,
    name: "Admin-Reports-ooto___es"
  }, {
    path: "/es/Admin/Reports/reports",
    component: _7a3ad286,
    name: "Admin-Reports-reports___es"
  }, {
    path: "/es/Admin/Reports/statistics",
    component: _c71502d6,
    name: "Admin-Reports-statistics___es"
  }, {
    path: "/es/Admin/Reports/surveys",
    component: _1632a752,
    name: "Admin-Reports-surveys___es"
  }, {
    path: "/es/Admin/Reports/team-scheduler",
    component: _879bdc86,
    name: "Admin-Reports-team-scheduler___es"
  }, {
    path: "/es/Admin/Sales/agreements",
    component: _83855bb0,
    name: "Admin-Sales-agreements___es"
  }, {
    path: "/es/Admin/Sales/certificates",
    component: _ee72d60a,
    name: "Admin-Sales-certificates___es"
  }, {
    path: "/es/Admin/Sales/credit-memos",
    component: _b68f0d38,
    name: "Admin-Sales-credit-memos___es"
  }, {
    path: "/es/Admin/Sales/invoices",
    component: _6db68ca5,
    name: "Admin-Sales-invoices___es"
  }, {
    path: "/es/Admin/Sales/orders",
    component: _441412e4,
    name: "Admin-Sales-orders___es"
  }, {
    path: "/es/Admin/Sales/quotes",
    component: _636fa876,
    name: "Admin-Sales-quotes___es"
  }, {
    path: "/es/Admin/Sales/returns",
    component: _52dec754,
    name: "Admin-Sales-returns___es"
  }, {
    path: "/es/Admin/Sales/shipments",
    component: _59ef2a2c,
    name: "Admin-Sales-shipments___es"
  }, {
    path: "/es/Admin/Sales/transactions",
    component: _45ffb814,
    name: "Admin-Sales-transactions___es"
  }, {
    path: "/es/Admin/Shop/attributes",
    component: _78bafbaa,
    name: "Admin-Shop-attributes___es"
  }, {
    path: "/es/Admin/Shop/categories",
    component: _1a7eadef,
    name: "Admin-Shop-categories___es"
  }, {
    path: "/es/Admin/Shop/cities",
    component: _a064cbc8,
    name: "Admin-Shop-cities___es"
  }, {
    path: "/es/Admin/Shop/collections",
    component: _2ea96c5c,
    name: "Admin-Shop-collections___es"
  }, {
    path: "/es/Admin/Shop/countries",
    component: _4b99dcb1,
    name: "Admin-Shop-countries___es"
  }, {
    path: "/es/Admin/Shop/coupons",
    component: _7b2cafca,
    name: "Admin-Shop-coupons___es"
  }, {
    path: "/es/Admin/Shop/inventory",
    component: _f94a714e,
    name: "Admin-Shop-inventory___es"
  }, {
    path: "/es/Admin/Shop/partners",
    component: _5c1fd7be,
    name: "Admin-Shop-partners___es"
  }, {
    path: "/es/Admin/Shop/product-types",
    component: _2e56f3d0,
    name: "Admin-Shop-product-types___es"
  }, {
    path: "/es/Admin/Shop/products",
    component: _e21c3012,
    name: "Admin-Shop-products___es"
  }, {
    path: "/es/Admin/Shop/shops",
    component: _6a4c543a,
    name: "Admin-Shop-shops___es"
  }, {
    path: "/es/Admin/Shop/states",
    component: _38f8af56,
    name: "Admin-Shop-states___es"
  }, {
    path: "/es/Admin/Shop/tax-rate",
    component: _37970d56,
    name: "Admin-Shop-tax-rate___es"
  }, {
    path: "/es/Admin/Shop/tax-rule",
    component: _0eeb551e,
    name: "Admin-Shop-tax-rule___es"
  }, {
    path: "/es/Admin/Shop/warehouses",
    component: _254b283a,
    name: "Admin-Shop-warehouses___es"
  }, {
    path: "/es/Admin/System/export-management",
    component: _7ee73ee0,
    name: "Admin-System-export-management___es"
  }, {
    path: "/es/Admin/System/general-settings",
    component: _81ef6398,
    name: "Admin-System-general-settings___es"
  }, {
    path: "/es/Admin/System/help",
    component: _35767b8d,
    name: "Admin-System-help___es"
  }, {
    path: "/es/Admin/System/import-management",
    component: _85524262,
    name: "Admin-System-import-management___es"
  }, {
    path: "/es/Admin/System/integrations",
    component: _0ea25e6b,
    name: "Admin-System-integrations___es"
  }, {
    path: "/es/Admin/System/knowledgebase",
    component: _4304a89a,
    name: "Admin-System-knowledgebase___es"
  }, {
    path: "/es/Admin/System/role-manager",
    component: _31b9c322,
    name: "Admin-System-role-manager___es"
  }, {
    path: "/es/Admin/System/settings",
    component: _5ba22522,
    name: "Admin-System-settings___es"
  }, {
    path: "/fr/Admin/Add-New/add-new-agreement",
    component: _1bc74b8c,
    name: "Admin-Add-New-add-new-agreement___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-article",
    component: _5cc64526,
    name: "Admin-Add-New-add-new-article___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-attribute",
    component: _19d819cc,
    name: "Admin-Add-New-add-new-attribute___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-campaign",
    component: _606c8e10,
    name: "Admin-Add-New-add-new-campaign___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-case",
    component: _28496c30,
    name: "Admin-Add-New-add-new-case___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-category",
    component: _6f8aa2fe,
    name: "Admin-Add-New-add-new-category___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-channel",
    component: _3c5826b3,
    name: "Admin-Add-New-add-new-channel___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-checklist",
    component: _4c7eabd6,
    name: "Admin-Add-New-add-new-checklist___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-city",
    component: _5b6c162a,
    name: "Admin-Add-New-add-new-city___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-collection",
    component: _a9866ac4,
    name: "Admin-Add-New-add-new-collection___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-contract",
    component: _028ccd12,
    name: "Admin-Add-New-add-new-contract___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-country",
    component: _58030074,
    name: "Admin-Add-New-add-new-country___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-coupon",
    component: _494337b4,
    name: "Admin-Add-New-add-new-coupon___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-currency",
    component: _dbe3d6de,
    name: "Admin-Add-New-add-new-currency___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-customer",
    component: _e8661444,
    name: "Admin-Add-New-add-new-customer___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-customergroup",
    component: _6c8dabde,
    name: "Admin-Add-New-add-new-customergroup___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-deepdive",
    component: _6a22d9e0,
    name: "Admin-Add-New-add-new-deepdive___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-email",
    component: _39e746cc,
    name: "Admin-Add-New-add-new-email___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-emailtemplates",
    component: _4a7fd0c6,
    name: "Admin-Add-New-add-new-emailtemplates___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-eosr",
    component: _454b95ee,
    name: "Admin-Add-New-add-new-eosr___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-event",
    component: _8538826c,
    name: "Admin-Add-New-add-new-event___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-fullfilment",
    component: _53db7ea8,
    name: "Admin-Add-New-add-new-fullfilment___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-gift-certificates",
    component: _a484482e,
    name: "Admin-Add-New-add-new-gift-certificates___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-glossary",
    component: _446aa01e,
    name: "Admin-Add-New-add-new-glossary___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-invoice",
    component: _0ec07046,
    name: "Admin-Add-New-add-new-invoice___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-knowledgebase",
    component: _94475c02,
    name: "Admin-Add-New-add-new-knowledgebase___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-lead",
    component: _f7f0cb48,
    name: "Admin-Add-New-add-new-lead___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-meeting",
    component: _114cd02a,
    name: "Admin-Add-New-add-new-meeting___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-newsletter",
    component: _fdbec98e,
    name: "Admin-Add-New-add-new-newsletter___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-newslettersubscriber%20copy",
    component: _95ec6cf8,
    name: "Admin-Add-New-add-new-newslettersubscriber copy___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-ooto",
    component: _249ef04a,
    name: "Admin-Add-New-add-new-ooto___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-opportunity",
    component: _4ab7c6fa,
    name: "Admin-Add-New-add-new-opportunity___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-page",
    component: _5a3e8c0f,
    name: "Admin-Add-New-add-new-page___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-partner",
    component: _661a1bf8,
    name: "Admin-Add-New-add-new-partner___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-pdftemplates",
    component: _39508807,
    name: "Admin-Add-New-add-new-pdftemplates___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-product",
    component: _59cebec2,
    name: "Admin-Add-New-add-new-product___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-producttype",
    component: _5c5ca759,
    name: "Admin-Add-New-add-new-producttype___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-project",
    component: _18080c6e,
    name: "Admin-Add-New-add-new-project___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-quote",
    component: _631fc9ac,
    name: "Admin-Add-New-add-new-quote___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-report",
    component: _2a26aa34,
    name: "Admin-Add-New-add-new-report___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-return",
    component: _06bc3430,
    name: "Admin-Add-New-add-new-return___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-review",
    component: _46039a58,
    name: "Admin-Add-New-add-new-review___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-rewards",
    component: _629b4854,
    name: "Admin-Add-New-add-new-rewards___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-role",
    component: _17205e76,
    name: "Admin-Add-New-add-new-role___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-schedule",
    component: _c92ff7d2,
    name: "Admin-Add-New-add-new-schedule___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-segment",
    component: _19969e3a,
    name: "Admin-Add-New-add-new-segment___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-shipment",
    component: _33dda99a,
    name: "Admin-Add-New-add-new-shipment___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-shop",
    component: _126f78f6,
    name: "Admin-Add-New-add-new-shop___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-staffmembers",
    component: _eec3328e,
    name: "Admin-Add-New-add-new-staffmembers___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-state",
    component: _3f303d41,
    name: "Admin-Add-New-add-new-state___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-survey",
    component: _e2470d4c,
    name: "Admin-Add-New-add-new-survey___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-tag",
    component: _62cd51ca,
    name: "Admin-Add-New-add-new-tag___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-target",
    component: _57ed5fde,
    name: "Admin-Add-New-add-new-target___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-task",
    component: _0e91f405,
    name: "Admin-Add-New-add-new-task___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-taxrate",
    component: _6694b68a,
    name: "Admin-Add-New-add-new-taxrate___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-taxrule",
    component: _3de8fe52,
    name: "Admin-Add-New-add-new-taxrule___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-ticket",
    component: _3394140c,
    name: "Admin-Add-New-add-new-ticket___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-visit",
    component: _2b8ed8fb,
    name: "Admin-Add-New-add-new-visit___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-warehouse",
    component: _25dd3e73,
    name: "Admin-Add-New-add-new-warehouse___fr"
  }, {
    path: "/fr/Admin/Add-New/add-new-zone",
    component: _599376ac,
    name: "Admin-Add-New-add-new-zone___fr"
  }, {
    path: "/fr/Admin/Content/blog",
    component: _9d529964,
    name: "Admin-Content-blog___fr"
  }, {
    path: "/fr/Admin/Content/glossary",
    component: _98c3f46c,
    name: "Admin-Content-glossary___fr"
  }, {
    path: "/fr/Admin/Content/media-manager",
    component: _52b993c8,
    name: "Admin-Content-media-manager___fr"
  }, {
    path: "/fr/Admin/Content/pages",
    component: _77a0f0c8,
    name: "Admin-Content-pages___fr"
  }, {
    path: "/fr/Admin/Content/projects",
    component: _033b73b4,
    name: "Admin-Content-projects___fr"
  }, {
    path: "/fr/Admin/Content/tags",
    component: _a76cb776,
    name: "Admin-Content-tags___fr"
  }, {
    path: "/fr/Admin/Customers/all-customers",
    component: _721d0311,
    name: "Admin-Customers-all-customers___fr"
  }, {
    path: "/fr/Admin/Customers/leads",
    component: _47c4b57f,
    name: "Admin-Customers-leads___fr"
  }, {
    path: "/fr/Admin/Customers/meetings",
    component: _1b5b8f40,
    name: "Admin-Customers-meetings___fr"
  }, {
    path: "/fr/Admin/Customers/online-customers",
    component: _4c8afaa3,
    name: "Admin-Customers-online-customers___fr"
  }, {
    path: "/fr/Admin/Customers/opportunities",
    component: _fd636ace,
    name: "Admin-Customers-opportunities___fr"
  }, {
    path: "/fr/Admin/Customers/segments",
    component: _71da3e68,
    name: "Admin-Customers-segments___fr"
  }, {
    path: "/fr/Admin/Customers/social-groups",
    component: _2109ea9c,
    name: "Admin-Customers-social-groups___fr"
  }, {
    path: "/fr/Admin/Customers/tasks",
    component: _0e8590f6,
    name: "Admin-Customers-tasks___fr"
  }, {
    path: "/fr/Admin/Marketing/checklists",
    component: _6c07dba6,
    name: "Admin-Marketing-checklists___fr"
  }, {
    path: "/fr/Admin/Marketing/communications",
    component: _334552f6,
    name: "Admin-Marketing-communications___fr"
  }, {
    path: "/fr/Admin/Marketing/contracts",
    component: _d40a98d0,
    name: "Admin-Marketing-contracts___fr"
  }, {
    path: "/fr/Admin/Marketing/events",
    component: _1416489c,
    name: "Admin-Marketing-events___fr"
  }, {
    path: "/fr/Admin/Marketing/invitations",
    component: _7fd3cdb1,
    name: "Admin-Marketing-invitations___fr"
  }, {
    path: "/fr/Admin/Marketing/newsletter",
    component: _b3b3f25c,
    name: "Admin-Marketing-newsletter___fr"
  }, {
    path: "/fr/Admin/Marketing/reviews",
    component: _3ceb965c,
    name: "Admin-Marketing-reviews___fr"
  }, {
    path: "/fr/Admin/Marketing/rewards",
    component: _73eba94a,
    name: "Admin-Marketing-rewards___fr"
  }, {
    path: "/fr/Admin/Marketing/seo",
    component: _311ab394,
    name: "Admin-Marketing-seo___fr"
  }, {
    path: "/fr/Admin/Marketing/ticketing",
    component: _ba50fe66,
    name: "Admin-Marketing-ticketing___fr"
  }, {
    path: "/fr/Admin/Marketing/training",
    component: _bcf7c29a,
    name: "Admin-Marketing-training___fr"
  }, {
    path: "/fr/Admin/Marketing/visits",
    component: _4d2d07a1,
    name: "Admin-Marketing-visits___fr"
  }, {
    path: "/fr/Admin/Reports/calendars",
    component: _ebc5751a,
    name: "Admin-Reports-calendars___fr"
  }, {
    path: "/fr/Admin/Reports/cases",
    component: _5b4be07e,
    name: "Admin-Reports-cases___fr"
  }, {
    path: "/fr/Admin/Reports/deep-dive",
    component: _0c2d9eb3,
    name: "Admin-Reports-deep-dive___fr"
  }, {
    path: "/fr/Admin/Reports/eosr",
    component: _79ab0e7b,
    name: "Admin-Reports-eosr___fr"
  }, {
    path: "/fr/Admin/Reports/ooto",
    component: _ebfd3d66,
    name: "Admin-Reports-ooto___fr"
  }, {
    path: "/fr/Admin/Reports/reports",
    component: _7a3ad286,
    name: "Admin-Reports-reports___fr"
  }, {
    path: "/fr/Admin/Reports/statistics",
    component: _c71502d6,
    name: "Admin-Reports-statistics___fr"
  }, {
    path: "/fr/Admin/Reports/surveys",
    component: _1632a752,
    name: "Admin-Reports-surveys___fr"
  }, {
    path: "/fr/Admin/Reports/team-scheduler",
    component: _879bdc86,
    name: "Admin-Reports-team-scheduler___fr"
  }, {
    path: "/fr/Admin/Sales/agreements",
    component: _83855bb0,
    name: "Admin-Sales-agreements___fr"
  }, {
    path: "/fr/Admin/Sales/certificates",
    component: _ee72d60a,
    name: "Admin-Sales-certificates___fr"
  }, {
    path: "/fr/Admin/Sales/credit-memos",
    component: _b68f0d38,
    name: "Admin-Sales-credit-memos___fr"
  }, {
    path: "/fr/Admin/Sales/invoices",
    component: _6db68ca5,
    name: "Admin-Sales-invoices___fr"
  }, {
    path: "/fr/Admin/Sales/orders",
    component: _441412e4,
    name: "Admin-Sales-orders___fr"
  }, {
    path: "/fr/Admin/Sales/quotes",
    component: _636fa876,
    name: "Admin-Sales-quotes___fr"
  }, {
    path: "/fr/Admin/Sales/returns",
    component: _52dec754,
    name: "Admin-Sales-returns___fr"
  }, {
    path: "/fr/Admin/Sales/shipments",
    component: _59ef2a2c,
    name: "Admin-Sales-shipments___fr"
  }, {
    path: "/fr/Admin/Sales/transactions",
    component: _45ffb814,
    name: "Admin-Sales-transactions___fr"
  }, {
    path: "/fr/Admin/Shop/attributes",
    component: _78bafbaa,
    name: "Admin-Shop-attributes___fr"
  }, {
    path: "/fr/Admin/Shop/categories",
    component: _1a7eadef,
    name: "Admin-Shop-categories___fr"
  }, {
    path: "/fr/Admin/Shop/cities",
    component: _a064cbc8,
    name: "Admin-Shop-cities___fr"
  }, {
    path: "/fr/Admin/Shop/collections",
    component: _2ea96c5c,
    name: "Admin-Shop-collections___fr"
  }, {
    path: "/fr/Admin/Shop/countries",
    component: _4b99dcb1,
    name: "Admin-Shop-countries___fr"
  }, {
    path: "/fr/Admin/Shop/coupons",
    component: _7b2cafca,
    name: "Admin-Shop-coupons___fr"
  }, {
    path: "/fr/Admin/Shop/inventory",
    component: _f94a714e,
    name: "Admin-Shop-inventory___fr"
  }, {
    path: "/fr/Admin/Shop/partners",
    component: _5c1fd7be,
    name: "Admin-Shop-partners___fr"
  }, {
    path: "/fr/Admin/Shop/product-types",
    component: _2e56f3d0,
    name: "Admin-Shop-product-types___fr"
  }, {
    path: "/fr/Admin/Shop/products",
    component: _e21c3012,
    name: "Admin-Shop-products___fr"
  }, {
    path: "/fr/Admin/Shop/shops",
    component: _6a4c543a,
    name: "Admin-Shop-shops___fr"
  }, {
    path: "/fr/Admin/Shop/states",
    component: _38f8af56,
    name: "Admin-Shop-states___fr"
  }, {
    path: "/fr/Admin/Shop/tax-rate",
    component: _37970d56,
    name: "Admin-Shop-tax-rate___fr"
  }, {
    path: "/fr/Admin/Shop/tax-rule",
    component: _0eeb551e,
    name: "Admin-Shop-tax-rule___fr"
  }, {
    path: "/fr/Admin/Shop/warehouses",
    component: _254b283a,
    name: "Admin-Shop-warehouses___fr"
  }, {
    path: "/fr/Admin/System/export-management",
    component: _7ee73ee0,
    name: "Admin-System-export-management___fr"
  }, {
    path: "/fr/Admin/System/general-settings",
    component: _81ef6398,
    name: "Admin-System-general-settings___fr"
  }, {
    path: "/fr/Admin/System/help",
    component: _35767b8d,
    name: "Admin-System-help___fr"
  }, {
    path: "/fr/Admin/System/import-management",
    component: _85524262,
    name: "Admin-System-import-management___fr"
  }, {
    path: "/fr/Admin/System/integrations",
    component: _0ea25e6b,
    name: "Admin-System-integrations___fr"
  }, {
    path: "/fr/Admin/System/knowledgebase",
    component: _4304a89a,
    name: "Admin-System-knowledgebase___fr"
  }, {
    path: "/fr/Admin/System/role-manager",
    component: _31b9c322,
    name: "Admin-System-role-manager___fr"
  }, {
    path: "/fr/Admin/System/settings",
    component: _5ba22522,
    name: "Admin-System-settings___fr"
  }, {
    path: "/es/Admin/Customers/customer/newcustomer",
    component: _0f36f970,
    name: "Admin-Customers-customer-newcustomer___es"
  }, {
    path: "/es/Admin/Edit/providers/id",
    component: _77c037a6,
    name: "Admin-Edit-providers-id___es"
  }, {
    path: "/es/Admin/Marketing/Email/email-designer",
    component: _d2581622,
    name: "Admin-Marketing-Email-email-designer___es"
  }, {
    path: "/fr/Admin/Customers/customer/newcustomer",
    component: _0f36f970,
    name: "Admin-Customers-customer-newcustomer___fr"
  }, {
    path: "/fr/Admin/Edit/providers/id",
    component: _77c037a6,
    name: "Admin-Edit-providers-id___fr"
  }, {
    path: "/fr/Admin/Marketing/Email/email-designer",
    component: _d2581622,
    name: "Admin-Marketing-Email-email-designer___fr"
  }, {
    path: "/es/Admin/Shop/Product/Edit/:id?",
    component: _3e76ee18,
    name: "Admin-Shop-Product-Edit-id___es"
  }, {
    path: "/fr/Admin/Shop/Product/Edit/:id?",
    component: _3e76ee18,
    name: "Admin-Shop-Product-Edit-id___fr"
  }, {
    path: "/Admin/Shop/Product/Edit/:id?",
    component: _3e76ee18,
    name: "Admin-Shop-Product-Edit-id___en"
  }, {
    path: "/es/Admin/Edit/agreement/:id?",
    component: _b0633852,
    name: "Admin-Edit-agreement-id___es"
  }, {
    path: "/es/Admin/Edit/article/:id?",
    component: _6d2fda2b,
    name: "Admin-Edit-article-id___es"
  }, {
    path: "/es/Admin/Edit/attribute/:id?",
    component: _03b58f85,
    name: "Admin-Edit-attribute-id___es"
  }, {
    path: "/es/Admin/Edit/cases/:id?",
    component: _528ada3e,
    name: "Admin-Edit-cases-id___es"
  }, {
    path: "/es/Admin/Edit/category/:id?",
    component: _27c6d7e5,
    name: "Admin-Edit-category-id___es"
  }, {
    path: "/es/Admin/Edit/channel/:id?",
    component: _f9842e84,
    name: "Admin-Edit-channel-id___es"
  }, {
    path: "/es/Admin/Edit/checklist/:id?",
    component: _852a988a,
    name: "Admin-Edit-checklist-id___es"
  }, {
    path: "/es/Admin/Edit/city/:id?",
    component: _79a3f698,
    name: "Admin-Edit-city-id___es"
  }, {
    path: "/es/Admin/Edit/collection/:id?",
    component: _60e02a05,
    name: "Admin-Edit-collection-id___es"
  }, {
    path: "/es/Admin/Edit/contracts/:id?",
    component: _37a33e20,
    name: "Admin-Edit-contracts-id___es"
  }, {
    path: "/es/Admin/Edit/country/:id?",
    component: _79d978ea,
    name: "Admin-Edit-country-id___es"
  }, {
    path: "/es/Admin/Edit/coupon/:id?",
    component: _26ef69fd,
    name: "Admin-Edit-coupon-id___es"
  }, {
    path: "/es/Admin/Edit/currency/:id?",
    component: _24cb2b9c,
    name: "Admin-Edit-currency-id___es"
  }, {
    path: "/es/Admin/Edit/customergroup/:id?",
    component: _c6295240,
    name: "Admin-Edit-customergroup-id___es"
  }, {
    path: "/es/Admin/Edit/deep-dive/:id?",
    component: _66b4d00c,
    name: "Admin-Edit-deep-dive-id___es"
  }, {
    path: "/es/Admin/Edit/email_template/:id?",
    component: _4576f946,
    name: "Admin-Edit-email_template-id___es"
  }, {
    path: "/es/Admin/Edit/event/:id?",
    component: _6ba2a4c7,
    name: "Admin-Edit-event-id___es"
  }, {
    path: "/es/Admin/Edit/fullfillment/:id?",
    component: _426d9fb3,
    name: "Admin-Edit-fullfillment-id___es"
  }, {
    path: "/es/Admin/Edit/gift-certificate/:id?",
    component: _75d0eae9,
    name: "Admin-Edit-gift-certificate-id___es"
  }, {
    path: "/es/Admin/Edit/glossary/:id?",
    component: _76f80ec5,
    name: "Admin-Edit-glossary-id___es"
  }, {
    path: "/es/Admin/Edit/invoice/:id?",
    component: _5f3e71d4,
    name: "Admin-Edit-invoice-id___es"
  }, {
    path: "/es/Admin/Edit/knowledgebase/:id?",
    component: _1c6c189c,
    name: "Admin-Edit-knowledgebase-id___es"
  }, {
    path: "/es/Admin/Edit/leads/:id?",
    component: _43fe912c,
    name: "Admin-Edit-leads-id___es"
  }, {
    path: "/es/Admin/Edit/meeting/:id?",
    component: _97eb0af4,
    name: "Admin-Edit-meeting-id___es"
  }, {
    path: "/es/Admin/Edit/newsletter/:id?",
    component: _8d44fb6c,
    name: "Admin-Edit-newsletter-id___es"
  }, {
    path: "/es/Admin/Edit/newslettersubscriber/:id?",
    component: _8a3d163c,
    name: "Admin-Edit-newslettersubscriber-id___es"
  }, {
    path: "/es/Admin/Edit/ooto/:id?",
    component: _4b13b9a8,
    name: "Admin-Edit-ooto-id___es"
  }, {
    path: "/es/Admin/Edit/opportunities/:id?",
    component: _262db390,
    name: "Admin-Edit-opportunities-id___es"
  }, {
    path: "/es/Admin/Edit/page/:id?",
    component: _99379418,
    name: "Admin-Edit-page-id___es"
  }, {
    path: "/es/Admin/Edit/partner/:id?",
    component: _59a912ce,
    name: "Admin-Edit-partner-id___es"
  }, {
    path: "/es/Admin/Edit/pdf_template/:id?",
    component: _755b655c,
    name: "Admin-Edit-pdf_template-id___es"
  }, {
    path: "/es/Admin/Edit/product-type/:id?",
    component: _1e99af6a,
    name: "Admin-Edit-product-type-id___es"
  }, {
    path: "/es/Admin/Edit/product/:id?",
    component: _3198c252,
    name: "Admin-Edit-product-id___es"
  }, {
    path: "/es/Admin/Edit/projects/:id?",
    component: _19d9a7e9,
    name: "Admin-Edit-projects-id___es"
  }, {
    path: "/es/Admin/Edit/quotes/:id?",
    component: _4f52c868,
    name: "Admin-Edit-quotes-id___es"
  }, {
    path: "/es/Admin/Edit/report/:id?",
    component: _6046bcaf,
    name: "Admin-Edit-report-id___es"
  }, {
    path: "/es/Admin/Edit/return/:id?",
    component: _e277df9a,
    name: "Admin-Edit-return-id___es"
  }, {
    path: "/es/Admin/Edit/review/:id?",
    component: _166e430b,
    name: "Admin-Edit-review-id___es"
  }, {
    path: "/es/Admin/Edit/reward/:id?",
    component: _358dcd14,
    name: "Admin-Edit-reward-id___es"
  }, {
    path: "/es/Admin/Edit/segment/:id?",
    component: _f6df86e4,
    name: "Admin-Edit-segment-id___es"
  }, {
    path: "/es/Admin/Edit/shipment/:id?",
    component: _669b92c9,
    name: "Admin-Edit-shipment-id___es"
  }, {
    path: "/es/Admin/Edit/shops/:id?",
    component: _3d09ba84,
    name: "Admin-Edit-shops-id___es"
  }, {
    path: "/es/Admin/Edit/state/:id?",
    component: _11f4cea0,
    name: "Admin-Edit-state-id___es"
  }, {
    path: "/es/Admin/Edit/tag/:id?",
    component: _d56980f2,
    name: "Admin-Edit-tag-id___es"
  }, {
    path: "/es/Admin/Edit/target/:id?",
    component: _c73b8e1c,
    name: "Admin-Edit-target-id___es"
  }, {
    path: "/es/Admin/Edit/tasks/:id?",
    component: _60bd235a,
    name: "Admin-Edit-tasks-id___es"
  }, {
    path: "/es/Admin/Edit/taxrate/:id?",
    component: _95742094,
    name: "Admin-Edit-taxrate-id___es"
  }, {
    path: "/es/Admin/Edit/taxrule/:id?",
    component: _affd75cc,
    name: "Admin-Edit-taxrule-id___es"
  }, {
    path: "/es/Admin/Edit/ticket/:id?",
    component: _5f2c8c52,
    name: "Admin-Edit-ticket-id___es"
  }, {
    path: "/es/Admin/Edit/visit/:id?",
    component: _5c157d94,
    name: "Admin-Edit-visit-id___es"
  }, {
    path: "/es/Admin/Edit/warehouse/:id?",
    component: _3e403b3e,
    name: "Admin-Edit-warehouse-id___es"
  }, {
    path: "/es/Admin/Edit/zone/:id?",
    component: _fb0b3512,
    name: "Admin-Edit-zone-id___es"
  }, {
    path: "/es/Admin/Marketing/Email/:id?",
    component: _2f2cdfd7,
    name: "Admin-Marketing-Email-id___es"
  }, {
    path: "/fr/Admin/Edit/agreement/:id?",
    component: _b0633852,
    name: "Admin-Edit-agreement-id___fr"
  }, {
    path: "/fr/Admin/Edit/article/:id?",
    component: _6d2fda2b,
    name: "Admin-Edit-article-id___fr"
  }, {
    path: "/fr/Admin/Edit/attribute/:id?",
    component: _03b58f85,
    name: "Admin-Edit-attribute-id___fr"
  }, {
    path: "/fr/Admin/Edit/cases/:id?",
    component: _528ada3e,
    name: "Admin-Edit-cases-id___fr"
  }, {
    path: "/fr/Admin/Edit/category/:id?",
    component: _27c6d7e5,
    name: "Admin-Edit-category-id___fr"
  }, {
    path: "/fr/Admin/Edit/channel/:id?",
    component: _f9842e84,
    name: "Admin-Edit-channel-id___fr"
  }, {
    path: "/fr/Admin/Edit/checklist/:id?",
    component: _852a988a,
    name: "Admin-Edit-checklist-id___fr"
  }, {
    path: "/fr/Admin/Edit/city/:id?",
    component: _79a3f698,
    name: "Admin-Edit-city-id___fr"
  }, {
    path: "/fr/Admin/Edit/collection/:id?",
    component: _60e02a05,
    name: "Admin-Edit-collection-id___fr"
  }, {
    path: "/fr/Admin/Edit/contracts/:id?",
    component: _37a33e20,
    name: "Admin-Edit-contracts-id___fr"
  }, {
    path: "/fr/Admin/Edit/country/:id?",
    component: _79d978ea,
    name: "Admin-Edit-country-id___fr"
  }, {
    path: "/fr/Admin/Edit/coupon/:id?",
    component: _26ef69fd,
    name: "Admin-Edit-coupon-id___fr"
  }, {
    path: "/fr/Admin/Edit/currency/:id?",
    component: _24cb2b9c,
    name: "Admin-Edit-currency-id___fr"
  }, {
    path: "/fr/Admin/Edit/customergroup/:id?",
    component: _c6295240,
    name: "Admin-Edit-customergroup-id___fr"
  }, {
    path: "/fr/Admin/Edit/deep-dive/:id?",
    component: _66b4d00c,
    name: "Admin-Edit-deep-dive-id___fr"
  }, {
    path: "/fr/Admin/Edit/email_template/:id?",
    component: _4576f946,
    name: "Admin-Edit-email_template-id___fr"
  }, {
    path: "/fr/Admin/Edit/event/:id?",
    component: _6ba2a4c7,
    name: "Admin-Edit-event-id___fr"
  }, {
    path: "/fr/Admin/Edit/fullfillment/:id?",
    component: _426d9fb3,
    name: "Admin-Edit-fullfillment-id___fr"
  }, {
    path: "/fr/Admin/Edit/gift-certificate/:id?",
    component: _75d0eae9,
    name: "Admin-Edit-gift-certificate-id___fr"
  }, {
    path: "/fr/Admin/Edit/glossary/:id?",
    component: _76f80ec5,
    name: "Admin-Edit-glossary-id___fr"
  }, {
    path: "/fr/Admin/Edit/invoice/:id?",
    component: _5f3e71d4,
    name: "Admin-Edit-invoice-id___fr"
  }, {
    path: "/fr/Admin/Edit/knowledgebase/:id?",
    component: _1c6c189c,
    name: "Admin-Edit-knowledgebase-id___fr"
  }, {
    path: "/fr/Admin/Edit/leads/:id?",
    component: _43fe912c,
    name: "Admin-Edit-leads-id___fr"
  }, {
    path: "/fr/Admin/Edit/meeting/:id?",
    component: _97eb0af4,
    name: "Admin-Edit-meeting-id___fr"
  }, {
    path: "/fr/Admin/Edit/newsletter/:id?",
    component: _8d44fb6c,
    name: "Admin-Edit-newsletter-id___fr"
  }, {
    path: "/fr/Admin/Edit/newslettersubscriber/:id?",
    component: _8a3d163c,
    name: "Admin-Edit-newslettersubscriber-id___fr"
  }, {
    path: "/fr/Admin/Edit/ooto/:id?",
    component: _4b13b9a8,
    name: "Admin-Edit-ooto-id___fr"
  }, {
    path: "/fr/Admin/Edit/opportunities/:id?",
    component: _262db390,
    name: "Admin-Edit-opportunities-id___fr"
  }, {
    path: "/fr/Admin/Edit/page/:id?",
    component: _99379418,
    name: "Admin-Edit-page-id___fr"
  }, {
    path: "/fr/Admin/Edit/partner/:id?",
    component: _59a912ce,
    name: "Admin-Edit-partner-id___fr"
  }, {
    path: "/fr/Admin/Edit/pdf_template/:id?",
    component: _755b655c,
    name: "Admin-Edit-pdf_template-id___fr"
  }, {
    path: "/fr/Admin/Edit/product-type/:id?",
    component: _1e99af6a,
    name: "Admin-Edit-product-type-id___fr"
  }, {
    path: "/fr/Admin/Edit/product/:id?",
    component: _3198c252,
    name: "Admin-Edit-product-id___fr"
  }, {
    path: "/fr/Admin/Edit/projects/:id?",
    component: _19d9a7e9,
    name: "Admin-Edit-projects-id___fr"
  }, {
    path: "/fr/Admin/Edit/quotes/:id?",
    component: _4f52c868,
    name: "Admin-Edit-quotes-id___fr"
  }, {
    path: "/fr/Admin/Edit/report/:id?",
    component: _6046bcaf,
    name: "Admin-Edit-report-id___fr"
  }, {
    path: "/fr/Admin/Edit/return/:id?",
    component: _e277df9a,
    name: "Admin-Edit-return-id___fr"
  }, {
    path: "/fr/Admin/Edit/review/:id?",
    component: _166e430b,
    name: "Admin-Edit-review-id___fr"
  }, {
    path: "/fr/Admin/Edit/reward/:id?",
    component: _358dcd14,
    name: "Admin-Edit-reward-id___fr"
  }, {
    path: "/fr/Admin/Edit/segment/:id?",
    component: _f6df86e4,
    name: "Admin-Edit-segment-id___fr"
  }, {
    path: "/fr/Admin/Edit/shipment/:id?",
    component: _669b92c9,
    name: "Admin-Edit-shipment-id___fr"
  }, {
    path: "/fr/Admin/Edit/shops/:id?",
    component: _3d09ba84,
    name: "Admin-Edit-shops-id___fr"
  }, {
    path: "/fr/Admin/Edit/state/:id?",
    component: _11f4cea0,
    name: "Admin-Edit-state-id___fr"
  }, {
    path: "/fr/Admin/Edit/tag/:id?",
    component: _d56980f2,
    name: "Admin-Edit-tag-id___fr"
  }, {
    path: "/fr/Admin/Edit/target/:id?",
    component: _c73b8e1c,
    name: "Admin-Edit-target-id___fr"
  }, {
    path: "/fr/Admin/Edit/tasks/:id?",
    component: _60bd235a,
    name: "Admin-Edit-tasks-id___fr"
  }, {
    path: "/fr/Admin/Edit/taxrate/:id?",
    component: _95742094,
    name: "Admin-Edit-taxrate-id___fr"
  }, {
    path: "/fr/Admin/Edit/taxrule/:id?",
    component: _affd75cc,
    name: "Admin-Edit-taxrule-id___fr"
  }, {
    path: "/fr/Admin/Edit/ticket/:id?",
    component: _5f2c8c52,
    name: "Admin-Edit-ticket-id___fr"
  }, {
    path: "/fr/Admin/Edit/visit/:id?",
    component: _5c157d94,
    name: "Admin-Edit-visit-id___fr"
  }, {
    path: "/fr/Admin/Edit/warehouse/:id?",
    component: _3e403b3e,
    name: "Admin-Edit-warehouse-id___fr"
  }, {
    path: "/fr/Admin/Edit/zone/:id?",
    component: _fb0b3512,
    name: "Admin-Edit-zone-id___fr"
  }, {
    path: "/fr/Admin/Marketing/Email/:id?",
    component: _2f2cdfd7,
    name: "Admin-Marketing-Email-id___fr"
  }, {
    path: "/Admin/Edit/agreement/:id?",
    component: _b0633852,
    name: "Admin-Edit-agreement-id___en"
  }, {
    path: "/Admin/Edit/article/:id?",
    component: _6d2fda2b,
    name: "Admin-Edit-article-id___en"
  }, {
    path: "/Admin/Edit/attribute/:id?",
    component: _03b58f85,
    name: "Admin-Edit-attribute-id___en"
  }, {
    path: "/Admin/Edit/cases/:id?",
    component: _528ada3e,
    name: "Admin-Edit-cases-id___en"
  }, {
    path: "/Admin/Edit/category/:id?",
    component: _27c6d7e5,
    name: "Admin-Edit-category-id___en"
  }, {
    path: "/Admin/Edit/channel/:id?",
    component: _f9842e84,
    name: "Admin-Edit-channel-id___en"
  }, {
    path: "/Admin/Edit/checklist/:id?",
    component: _852a988a,
    name: "Admin-Edit-checklist-id___en"
  }, {
    path: "/Admin/Edit/city/:id?",
    component: _79a3f698,
    name: "Admin-Edit-city-id___en"
  }, {
    path: "/Admin/Edit/collection/:id?",
    component: _60e02a05,
    name: "Admin-Edit-collection-id___en"
  }, {
    path: "/Admin/Edit/contracts/:id?",
    component: _37a33e20,
    name: "Admin-Edit-contracts-id___en"
  }, {
    path: "/Admin/Edit/country/:id?",
    component: _79d978ea,
    name: "Admin-Edit-country-id___en"
  }, {
    path: "/Admin/Edit/coupon/:id?",
    component: _26ef69fd,
    name: "Admin-Edit-coupon-id___en"
  }, {
    path: "/Admin/Edit/currency/:id?",
    component: _24cb2b9c,
    name: "Admin-Edit-currency-id___en"
  }, {
    path: "/Admin/Edit/customergroup/:id?",
    component: _c6295240,
    name: "Admin-Edit-customergroup-id___en"
  }, {
    path: "/Admin/Edit/deep-dive/:id?",
    component: _66b4d00c,
    name: "Admin-Edit-deep-dive-id___en"
  }, {
    path: "/Admin/Edit/email_template/:id?",
    component: _4576f946,
    name: "Admin-Edit-email_template-id___en"
  }, {
    path: "/Admin/Edit/event/:id?",
    component: _6ba2a4c7,
    name: "Admin-Edit-event-id___en"
  }, {
    path: "/Admin/Edit/fullfillment/:id?",
    component: _426d9fb3,
    name: "Admin-Edit-fullfillment-id___en"
  }, {
    path: "/Admin/Edit/gift-certificate/:id?",
    component: _75d0eae9,
    name: "Admin-Edit-gift-certificate-id___en"
  }, {
    path: "/Admin/Edit/glossary/:id?",
    component: _76f80ec5,
    name: "Admin-Edit-glossary-id___en"
  }, {
    path: "/Admin/Edit/invoice/:id?",
    component: _5f3e71d4,
    name: "Admin-Edit-invoice-id___en"
  }, {
    path: "/Admin/Edit/knowledgebase/:id?",
    component: _1c6c189c,
    name: "Admin-Edit-knowledgebase-id___en"
  }, {
    path: "/Admin/Edit/leads/:id?",
    component: _43fe912c,
    name: "Admin-Edit-leads-id___en"
  }, {
    path: "/Admin/Edit/meeting/:id?",
    component: _97eb0af4,
    name: "Admin-Edit-meeting-id___en"
  }, {
    path: "/Admin/Edit/newsletter/:id?",
    component: _8d44fb6c,
    name: "Admin-Edit-newsletter-id___en"
  }, {
    path: "/Admin/Edit/newslettersubscriber/:id?",
    component: _8a3d163c,
    name: "Admin-Edit-newslettersubscriber-id___en"
  }, {
    path: "/Admin/Edit/ooto/:id?",
    component: _4b13b9a8,
    name: "Admin-Edit-ooto-id___en"
  }, {
    path: "/Admin/Edit/opportunities/:id?",
    component: _262db390,
    name: "Admin-Edit-opportunities-id___en"
  }, {
    path: "/Admin/Edit/page/:id?",
    component: _99379418,
    name: "Admin-Edit-page-id___en"
  }, {
    path: "/Admin/Edit/partner/:id?",
    component: _59a912ce,
    name: "Admin-Edit-partner-id___en"
  }, {
    path: "/Admin/Edit/pdf_template/:id?",
    component: _755b655c,
    name: "Admin-Edit-pdf_template-id___en"
  }, {
    path: "/Admin/Edit/product-type/:id?",
    component: _1e99af6a,
    name: "Admin-Edit-product-type-id___en"
  }, {
    path: "/Admin/Edit/product/:id?",
    component: _3198c252,
    name: "Admin-Edit-product-id___en"
  }, {
    path: "/Admin/Edit/projects/:id?",
    component: _19d9a7e9,
    name: "Admin-Edit-projects-id___en"
  }, {
    path: "/Admin/Edit/quotes/:id?",
    component: _4f52c868,
    name: "Admin-Edit-quotes-id___en"
  }, {
    path: "/Admin/Edit/report/:id?",
    component: _6046bcaf,
    name: "Admin-Edit-report-id___en"
  }, {
    path: "/Admin/Edit/return/:id?",
    component: _e277df9a,
    name: "Admin-Edit-return-id___en"
  }, {
    path: "/Admin/Edit/review/:id?",
    component: _166e430b,
    name: "Admin-Edit-review-id___en"
  }, {
    path: "/Admin/Edit/reward/:id?",
    component: _358dcd14,
    name: "Admin-Edit-reward-id___en"
  }, {
    path: "/Admin/Edit/segment/:id?",
    component: _f6df86e4,
    name: "Admin-Edit-segment-id___en"
  }, {
    path: "/Admin/Edit/shipment/:id?",
    component: _669b92c9,
    name: "Admin-Edit-shipment-id___en"
  }, {
    path: "/Admin/Edit/shops/:id?",
    component: _3d09ba84,
    name: "Admin-Edit-shops-id___en"
  }, {
    path: "/Admin/Edit/state/:id?",
    component: _11f4cea0,
    name: "Admin-Edit-state-id___en"
  }, {
    path: "/Admin/Edit/tag/:id?",
    component: _d56980f2,
    name: "Admin-Edit-tag-id___en"
  }, {
    path: "/Admin/Edit/target/:id?",
    component: _c73b8e1c,
    name: "Admin-Edit-target-id___en"
  }, {
    path: "/Admin/Edit/tasks/:id?",
    component: _60bd235a,
    name: "Admin-Edit-tasks-id___en"
  }, {
    path: "/Admin/Edit/taxrate/:id?",
    component: _95742094,
    name: "Admin-Edit-taxrate-id___en"
  }, {
    path: "/Admin/Edit/taxrule/:id?",
    component: _affd75cc,
    name: "Admin-Edit-taxrule-id___en"
  }, {
    path: "/Admin/Edit/ticket/:id?",
    component: _5f2c8c52,
    name: "Admin-Edit-ticket-id___en"
  }, {
    path: "/Admin/Edit/visit/:id?",
    component: _5c157d94,
    name: "Admin-Edit-visit-id___en"
  }, {
    path: "/Admin/Edit/warehouse/:id?",
    component: _3e403b3e,
    name: "Admin-Edit-warehouse-id___en"
  }, {
    path: "/Admin/Edit/zone/:id?",
    component: _fb0b3512,
    name: "Admin-Edit-zone-id___en"
  }, {
    path: "/Admin/Marketing/Email/:id?",
    component: _2f2cdfd7,
    name: "Admin-Marketing-Email-id___en"
  }, {
    path: "/",
    component: _8c3791c0,
    name: "index___en"
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config._app && config._app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
