query MyQuery {
  allCategoriesList {
    content
    country
    description
    id
    image
    metaDescription
    metaKeywords
    metaTitle
    metaUrl
    name
    nodeId
    product
    status
    thumbnail
    visibility
    websites
  }
}