query allCouponsList {
  allCouponsList {
    articles
    categories
    customers
    discount
    excerpt
    expiration
    image
    id
    prodId
    name
    nodeId
    products
    published
    users
  }
}