query MyQuery {
  allOccassionsList {
    id
    description
    name
    products
    tags
    wishlists
    category
    code
    created_at
    product {
      name
      price
      id
    }
    wishlist {
      id
      name
      products
    }
  }
}
