query MyQuery {
  products {
    attributes
    brand
    categories
    content
    contract
    cost_string
    country
    created_at
    customer_type
    family
    file
    format
    height
    id
    image
    manufacture
    manufacturer_part_number
    occassions
    name
    meta_url
    meta_title
    meta_keywords
    meta_description
    part_number
    price
    product
    quantity_per_source
    related_product
    salable_quantity
    short_description
    size
    sku
    status
    stock_status
    tags
    tax_class
    thumbnail
    types
    variants
    visibility
    websites
    weight
    zone
  }
}
