query allShopsList {
  allShopsList {
    articles
    categories
    comments
    country
    coupons
    customers
    description
    giftCertificates
    id
    image
    invoices
    name
    nodeId
    physicalStore
    polls
    products
    quotes
    rating
    reports
    reviews
    rewardPoints
    specialDiscounts
    statistics
    stocks
    tags
    website
    type
    users
  }
}