query MyQuery {
  allWarehousesList {
    status
    state
    products
    postal
    nodeId
    name
    isPublic
    image
    id
    description
    createdAt
    country
    city
    category
  }
}