query allChecklistsList {
  allChecklistsList {
    country
    createdAt
    description
    id
    location
    manager
    media
    nodeId
    prodId
    project
    region
    regionalManager
    ticket
    username
    trainingsByChecklistsList {
      id
      assignments
    }
    statesByTrainingChecklistsAndStateList {
      id
      name
    }
    productsByTrainingChecklistsAndProductsList {
      id
      name
    }
  }
}