query invitations {
  invitations {
    id
    grandTotalPurchased
    email
    createdAt
    content
    billingAddress
    invoiceDate
    media
    nodeId
    orderNumber
    paymentMethod
    shippingAddress
    status
  }
}