query MyQuery {
  allInvoicesList {
    id
    grandTotalPurchased
    grandTotalBase
    email
    customerName
    billingAddress
    customerGroup
    billToName
    invoice
    invoiceDate
    nodeId
    orderNumber
    paymentMethod
    shippingAddress
    shippingAndHandling
    shippingInformation
    status
    subtotal
  }
}